In [1]:
import pandas as pd 
import numpy as np

In [2]:
print("Simpal")

Simpal

In [3]:
df = pd.read_csv(r'C:\Users\DELL\Desktop\NLP\IMDB Dataset.csv')

In [4]:
df.sample(4)

                                                  review sentiment
40373  This is the biggest insult to TMNT ever. Fortu...  negative
29128  I have enjoyed Criminal Intent series of Law a...  positive
18183  The major fault in this film is that it is imp...  negative
9008   When I was little, my parents got this movie f...  positive

In [5]:
# Problem 1

# Apply all the preprocessing techniques that you think are necessary

import re 
def html_tag_remover(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

In [6]:
df['review'] = df['review'].apply(html_tag_remover)

In [7]:
df['review'] = df['review'].str.lower()

In [8]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [9]:
def remove_punchuation(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [10]:
import string, time 
exclude = string.punctuation

In [11]:
df['review']=df['review'].apply(remove_punchuation)

In [12]:
df.sample(3)

                                                  review sentiment
29967  just utter trash im a huge fan of the cusacks ...  negative
41512  it starts off pretty well with the accident an...  negative
40130  i thought this movie was good i loved the plot...  positive

In [13]:
# Problem 2

# Find out the number of words in the entire corpus and also the total number of unique words(vocabulary) using just python

In [17]:
total_word = df['review'].str.split().str.len().sum()

In [18]:
total_word

np.int64(11312801)

In [21]:
unique_word = set() 

for i in df['review']:

    words = i.split() 
    for j in words:
        unique_word.add(j) 

print(len(unique_word))

222751

In [23]:
# Problem 3

# Apply One Hot Encoding

In [28]:
from sklearn.feature_extraction.text import CountVectorizer 
cv = CountVectorizer(binary=True,max_features=5000) 
x=cv.fit_transform(df['review'])

In [29]:
x.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(50000, 5000))

In [30]:
print(x.shape)

(50000, 5000)

In [31]:
# Problem 4

# Apply bag words and find the vocabulary also find the times each word has occured

In [33]:
cv = CountVectorizer(max_features=500) 
BoW=cv.fit_transform(df['review'])

In [38]:
print(cv.vocabulary_)

{'one': np.int64(299), 'of': np.int64(292), 'the': np.int64(402), 'other': np.int64(303), 'has': np.int64(180), 'that': np.int64(400), 'after': np.int64(10), 'watching': np.int64(458), 'just': np.int64(220), 'episode': np.int64(120), 'youll': np.int64(496), 'be': np.int64(39), 'they': np.int64(409), 'are': np.int64(29), 'right': np.int64(343), 'as': np.int64(31), 'this': np.int64(414), 'is': np.int64(212), 'what': np.int64(464), 'with': np.int64(475), 'first': np.int64(148), 'thing': np.int64(411), 'me': np.int64(262), 'about': np.int64(2), 'was': np.int64(453), 'its': np.int64(215), 'and': np.int64(24), 'scenes': np.int64(350), 'which': np.int64(467), 'set': np.int64(363), 'in': np.int64(208), 'from': np.int64(154), 'go': np.int64(168), 'not': np.int64(289), 'show': np.int64(371), 'for': np.int64(150), 'or': np.int64(301), 'no': np.int64(288), 'to': np.int64(424), 'sex': np.int64(365), 'classic': np.int64(76), 'use': np.int64(444), 'called': np.int64(63), 'given': np.int64(166), 'it': np.int64(214), 'on': np.int64(297), 'an': np.int64(23), 'where': np.int64(466), 'all': np.int64(13), 'have': np.int64(181), 'face': np.int64(131), 'so': np.int64(377), 'high': np.int64(189), 'home': np.int64(195), 'death': np.int64(89), 'never': np.int64(283), 'far': np.int64(136), 'would': np.int64(487), 'say': np.int64(348), 'main': np.int64(253), 'fact': np.int64(132), 'goes': np.int64(169), 'shows': np.int64(372), 'pretty': np.int64(328), 'doesnt': np.int64(100), 'around': np.int64(30), 'ever': np.int64(123), 'saw': np.int64(347), 'couldnt': np.int64(82), 'but': np.int64(61), 'watched': np.int64(457), 'more': np.int64(271), 'got': np.int64(172), 'out': np.int64(306), 'kill': np.int64(223), 'get': np.int64(160), 'away': np.int64(34), 'well': np.int64(461), 'being': np.int64(48), 'into': np.int64(211), 'their': np.int64(403), 'you': np.int64(495), 'may': np.int64(260), 'become': np.int64(42), 'if': np.int64(206), 'can': np.int64(66), 'your': np.int64(498), 'side': np.int64(373), 'wonderful': np.int64(479), 'little': np.int64(240), 'production': np.int64(331), 'very': np.int64(447), 'gives': np.int64(167), 'sense': np.int64(361), 'entire': np.int64(119), 'piece': np.int64(319), 'actors': np.int64(8), 'michael': np.int64(265), 'only': np.int64(300), 'he': np.int64(183), 'down': np.int64(104), 'too': np.int64(426), 'truly': np.int64(431), 'see': np.int64(355), 'by': np.int64(62), 'worth': np.int64(486), 'written': np.int64(489), 'great': np.int64(173), 'comedy': np.int64(78), 'his': np.int64(192), 'life': np.int64(235), 'really': np.int64(338), 'comes': np.int64(79), 'things': np.int64(412), 'rather': np.int64(335), 'than': np.int64(399), 'then': np.int64(405), 'plays': np.int64(324), 'our': np.int64(305), 'every': np.int64(124), 'done': np.int64(102), 'thought': np.int64(417), 'way': np.int64(459), 'time': np.int64(421), 'plot': np.int64(325), 'dialogue': np.int64(92), 'characters': np.int64(73), 'even': np.int64(122), 'killer': np.int64(224), 'while': np.int64(468), 'some': np.int64(378), 'when': np.int64(465), 'point': np.int64(326), 'still': np.int64(388), 'style': np.int64(391), 'many': np.int64(258), 'us': np.int64(443), 'most': np.int64(272), 'id': np.int64(204), 'at': np.int64(32), 'years': np.int64(492), 'ive': np.int64(217), 'been': np.int64(44), 'she': np.int64(366), 'her': np.int64(186), 'young': np.int64(497), 'interesting': np.int64(210), 'friends': np.int64(153), 'theres': np.int64(407), 'family': np.int64(133), 'boy': np.int64(59), 'movie': np.int64(274), 'youre': np.int64(499), 'going': np.int64(170), 'make': np.int64(254), 'film': np.int64(142), 'must': np.int64(279), 'drama': np.int64(105), 'like': np.int64(236), 'real': np.int64(337), 'we': np.int64(460), 'totally': np.int64(428), 'instead': np.int64(209), '10': np.int64(0), 'playing': np.int64(323), 'them': np.int64(404), 'love': np.int64(249), 'money': np.int64(270), 'watch': np.int64(456), 'mr': np.int64(276), 'human': np.int64(202), 'seems': np.int64(359), 'do': np.int64(98), 'people': np.int64(312), 'different': np.int64(95), 'play': np.int64(321), 'same': np.int64(346), 'director': np.int64(97), 'action': np.int64(6), 'new': np.int64(284), 'these': np.int64(408), 'each': np.int64(108), 'another': np.int64(25), 'next': np.int64(285), 'person': np.int64(317), 'know': np.int64(226), 'look': np.int64(244), 'how': np.int64(200), 'live': np.int64(241), 'world': np.int64(483), 'own': np.int64(308), 'gets': np.int64(161), 'picture': np.int64(318), 'big': np.int64(53), 'best': np.int64(50), 'place': np.int64(320), 'find': np.int64(146), 'case': np.int64(69), 'acting': np.int64(5), 'good': np.int64(171), 'under': np.int64(438), 'direction': np.int64(96), 'rest': np.int64(342), 'cast': np.int64(70), 'come': np.int64(77), 'work': np.int64(481), 'probably': np.int64(329), 'my': np.int64(280), 'favorite': np.int64(138), 'story': np.int64(389), 'boring': np.int64(57), 'old': np.int64(296), 'despite': np.int64(91), 'having': np.int64(182), 'seen': np.int64(360), 'times': np.int64(422), 'last': np.int64(227), 'performance': np.int64(314), 'few': np.int64(141), 'kids': np.int64(222), 'children': np.int64(74), 'makes': np.int64(255), 'fun': np.int64(156), 'had': np.int64(177), 'up': np.int64(442), 'sure': np.int64(394), 'series': np.int64(362), 'back': np.int64(36), 'black': np.int64(55), 'white': np.int64(469), 'tv': np.int64(436), 'were': np.int64(463), 'need': np.int64(282), 'any': np.int64(26), 'believe': np.int64(49), 'nice': np.int64(286), 'read': np.int64(336), 'lines': np.int64(239), 'let': np.int64(234), 'amazing': np.int64(21), 'idea': np.int64(205), 'off': np.int64(293), 'funny': np.int64(157), 'waste': np.int64(455), 'writing': np.int64(488), 'bad': np.int64(37), 'performances': np.int64(315), 'almost': np.int64(14), 'entertaining': np.int64(118), 'hard': np.int64(179), 'original': np.int64(302), 'also': np.int64(17), 'such': np.int64(392), 'felt': np.int64(140), 'give': np.int64(165), 'stars': np.int64(386), 'made': np.int64(252), 'now': np.int64(291), 'awful': np.int64(35), 'cant': np.int64(67), 'here': np.int64(187), 'looking': np.int64(245), 'films': np.int64(143), 'worst': np.int64(485), 'played': np.int64(322), 'less': np.int64(233), 'looks': np.int64(246), 'end': np.int64(113), 'least': np.int64(231), 'making': np.int64(256), 'bit': np.int64(54), 'will': np.int64(474), 'liked': np.int64(237), 'those': np.int64(415), 'based': np.int64(38), 'everything': np.int64(126), 'didnt': np.int64(94), 'low': np.int64(251), 'budget': np.int64(60), 'thats': np.int64(401), 'problem': np.int64(330), 'itself': np.int64(216), 'there': np.int64(406), 'lost': np.int64(247), 'who': np.int64(470), 'something': np.int64(380), 'better': np.int64(51), 'try': np.int64(432), 'came': np.int64(64), 'scene': np.int64(349), 'men': np.int64(264), 'horror': np.int64(198), 'movies': np.int64(275), 'beautiful': np.int64(40), 'woman': np.int64(477), 'might': np.int64(266), 'care': np.int64(68), 'much': np.int64(277), 'year': np.int64(491), 'later': np.int64(228), 'loved': np.int64(250), 'star': np.int64(385), 'early': np.int64(109), 'since': np.int64(375), 'im': np.int64(207), 'fan': np.int64(134), 'again': np.int64(11), 'enjoyed': np.int64(116), 'maybe': np.int64(261), 'long': np.int64(243), 'before': np.int64(45), 'game': np.int64(158), 'should': np.int64(370), 'together': np.int64(425), 'along': np.int64(15), 'three': np.int64(418), 'actually': np.int64(9), 'yes': np.int64(493), 'however': np.int64(201), 'hes': np.int64(188), 'true': np.int64(430), 'whole': np.int64(471), 'dont': np.int64(103), 'evil': np.int64(127), 'reason': np.int64(339), 'did': np.int64(93), 'until': np.int64(441), 'laugh': np.int64(229), 'take': np.int64(395), 'him': np.int64(190), 'minutes': np.int64(268), 'screen': np.int64(352), 'trying': np.int64(433), 'why': np.int64(472), 'because': np.int64(41), 'keep': np.int64(221), 'does': np.int64(99), 'man': np.int64(257), 'kind': np.int64(225), 'sort': np.int64(382), 'school': np.int64(351), 'supposed': np.int64(393), 'quite': np.int64(334), 'could': np.int64(81), 'simply': np.int64(374), 'title': np.int64(423), 'excellent': np.int64(129), 'always': np.int64(19), 'feel': np.int64(139), 'character': np.int64(72), 'version': np.int64(446), 'special': np.int64(384), 'effects': np.int64(110), 'enjoy': np.int64(115), 'top': np.int64(427), 'horrible': np.int64(197), 'wasnt': np.int64(454), 'wanted': np.int64(450), 'final': np.int64(144), 'beginning': np.int64(46), 'both': np.int64(58), 'someone': np.int64(379), 'tell': np.int64(397), 'line': np.int64(238), 'either': np.int64(111), 'remember': np.int64(341), 'cinema': np.int64(75), 'dark': np.int64(85), 'actor': np.int64(7), 'think': np.int64(413), 'shot': np.int64(369), 'anyone': np.int64(27), 'dvd': np.int64(107), 'others': np.int64(304), 'against': np.int64(12), 'fine': np.int64(147), 'script': np.int64(353), 'enough': np.int64(117), 'couple': np.int64(83), 'wrong': np.int64(490), 'guy': np.int64(175), 'especially': np.int64(121), 'full': np.int64(155), 'john': np.int64(219), 'girl': np.int64(163), 'help': np.int64(185), 'turn': np.int64(434), 'terrible': np.int64(398), 'women': np.int64(478), 'absolutely': np.int64(3), 'wont': np.int64(480), 'although': np.int64(18), 'isnt': np.int64(213), 'anything': np.int64(28), 'music': np.int64(278), 'takes': np.int64(396), 'start': np.int64(387), 'am': np.int64(20), 'matter': np.int64(259), 'used': np.int64(445), 'several': np.int64(364), 'theyre': np.int64(410), 'worse': np.int64(484), 'over': np.int64(307), 'night': np.int64(287), 'stupid': np.int64(390), 'shes': np.int64(367), 'part': np.int64(309), 'though': np.int64(416), 'role': np.int64(344), 'job': np.int64(218), 'unfortunately': np.int64(440), 'mind': np.int64(267), 'want': np.int64(449), 'nothing': np.int64(290), 'wants': np.int64(451), 'guess': np.int64(174), 'else': np.int64(112), 'audience': np.int64(33), 'lot': np.int64(248), 'once': np.int64(298), 'hollywood': np.int64(194), 'behind': np.int64(47), 'war': np.int64(452), 'poor': np.int64(327), 'seemed': np.int64(358), 'able': np.int64(1), 'seem': np.int64(357), 'becomes': np.int64(43), 'left': np.int64(232), 'turns': np.int64(435), 'course': np.int64(84), 'put': np.int64(332), 'perhaps': np.int64(316), 'two': np.int64(437), 'father': np.int64(137), 'mother': np.int64(273), 'past': np.int64(311), 'between': np.int64(52), 'lives': np.int64(242), 'second': np.int64(354), 'small': np.int64(376), 'works': np.int64(482), 'himself': np.int64(191), 'finally': np.int64(145), 'house': np.int64(199), 'short': np.int64(368), 'through': np.int64(419), 'video': np.int64(448), 'quality': np.int64(333), 'yet': np.int64(494), 'without': np.int64(476), 'half': np.int64(178), 'days': np.int64(87), 'friend': np.int64(152), 'during': np.int64(106), 'expect': np.int64(130), 'gave': np.int64(159), 'lead': np.int64(230), 'certainly': np.int64(71), 'humor': np.int64(203), 'throughout': np.int64(420), 'act': np.int64(4), 'completely': np.int64(80), 'hope': np.int64(196), 'camera': np.int64(65), 'went': np.int64(462), 'recommend': np.int64(340), 'book': np.int64(56), 'moments': np.int64(269), 'ending': np.int64(114), 'example': np.int64(128), 'american': np.int64(22), 'parts': np.int64(310), 'head': np.int64(184), 'wife': np.int64(473), 'son': np.int64(381), 'getting': np.int64(162), 'sound': np.int64(383), 'already': np.int64(16), 'found': np.int64(151), 'day': np.int64(86), 'seeing': np.int64(356), 'dead': np.int64(88), 'fans': np.int64(135), 'often': np.int64(294), 'perfect': np.int64(313), 'definitely': np.int64(90), 'name': np.int64(281), 'everyone': np.int64(125), 'doing': np.int64(101), 'tries': np.int64(429), 'flick': np.int64(149), 'girls': np.int64(164), 'guys': np.int64(176), 'oh': np.int64(295), 'mean': np.int64(263), 'said': np.int64(345), 'understand': np.int64(439), 'history': np.int64(193)}

In [39]:
#  find the times each word has occured
import numpy as np 
words = cv.get_feature_names_out() 

counts = np.array(BoW.sum(axis=0)).flatten() 

for word, count in zip(words, counts):
    print(word, ':', count)

10 : 4174
able : 2578
about : 33844
absolutely : 2972
act : 2376
acting : 12399
action : 5908
actor : 4243
actors : 8763
actually : 8363
after : 14399
again : 7355
against : 2769
all : 44503
almost : 6152
along : 3629
already : 2628
also : 17483
although : 4618
always : 6262
am : 5700
amazing : 2440
american : 4152
an : 42663
and : 319438
another : 8184
any : 14960
anyone : 5119
anything : 5648
are : 58165
around : 6980
as : 90049
at : 46166
audience : 4060
away : 5274
awful : 3180
back : 9181
bad : 17647
based : 2681
be : 52717
beautiful : 4104
because : 17524
become : 2927
becomes : 2640
been : 18257
before : 8254
beginning : 2706
behind : 2325
being : 12987
believe : 4925
best : 12282
better : 11037
between : 6505
big : 6663
bit : 5863
black : 3852
book : 4474
boring : 3464
both : 6661
boy : 2735
budget : 3043
but : 80340
by : 43933
called : 2592
came : 3297
camera : 3200
can : 21849
cant : 7467
care : 2652
case : 2892
cast : 7149
certainly : 2931
character : 12914
characters : 14656
children : 2597
cinema : 2679
classic : 3429
come : 6136
comedy : 6087
comes : 4736
completely : 3788
could : 15140
couldnt : 3035
couple : 3380
course : 4788
dark : 2667
day : 4666
days : 2506
dead : 3388
death : 3696
definitely : 3031
despite : 2482
dialogue : 2973
did : 12343
didnt : 8781
different : 4584
direction : 2587
director : 7302
do : 17703
does : 11472
doesnt : 8862
doing : 3055
done : 5849
dont : 16580
down : 6908
drama : 2551
during : 4238
dvd : 4563
each : 5155
early : 3017
effects : 4347
either : 3430
else : 3713
end : 10514
ending : 4519
enjoy : 3487
enjoyed : 2401
enough : 6740
entertaining : 2797
entire : 2855
episode : 3040
especially : 4796
even : 24285
ever : 11620
every : 7860
everyone : 4151
everything : 4614
evil : 2593
example : 2608
excellent : 3994
expect : 2313
face : 2966
fact : 6821
family : 5503
fan : 3811
fans : 2628
far : 5728
father : 3345
favorite : 2341
feel : 5657
felt : 2852
few : 7900
film : 74479
films : 15284
final : 2599
finally : 2764
find : 8172
fine : 2485
first : 16840
flick : 2333
for : 86140
found : 5125
friend : 2724
friends : 3642
from : 40079
full : 3256
fun : 5130
funny : 8303
game : 2560
gave : 2401
get : 18183
gets : 6249
getting : 3286
girl : 5001
girls : 2511
give : 6631
given : 3499
gives : 3063
go : 9570
goes : 4708
going : 8020
good : 28483
got : 6912
great : 17719
guess : 2605
guy : 5968
guys : 2963
had : 21965
half : 3501
hard : 4720
has : 32881
have : 55020
having : 4792
he : 51799
head : 2877
help : 3620
her : 34214
here : 9971
hes : 5688
high : 3812
him : 16933
himself : 4052
his : 57203
history : 2428
hollywood : 3337
home : 3518
hope : 2857
horrible : 2454
horror : 6649
house : 3756
how : 17287
however : 6406
human : 3065
humor : 2634
id : 2565
idea : 3957
if : 31931
im : 8996
in : 183139
instead : 4137
interesting : 6016
into : 17793
is : 210064
isnt : 6278
it : 151368
its : 47791
itself : 3086
ive : 6421
job : 4315
john : 3969
just : 34681
keep : 3201
kids : 3692
kill : 2406
killer : 2388
kind : 5442
know : 12269
last : 5598
later : 4076
laugh : 2765
lead : 2620
least : 6035
left : 4072
less : 3527
let : 3252
life : 11682
like : 38830
liked : 2920
line : 3341
lines : 2977
little : 12311
live : 2816
lives : 2585
long : 6300
look : 8077
looking : 4571
looks : 4491
lost : 2839
lot : 7978
love : 12547
loved : 2874
low : 2567
made : 15408
main : 4574
make : 15284
makes : 8279
making : 4965
man : 10269
many : 13261
matter : 2316
may : 6529
maybe : 4455
me : 20773
mean : 3177
men : 3544
michael : 2352
might : 5727
mind : 3535
minutes : 5678
moments : 3177
money : 4310
more : 27629
most : 17116
mother : 2808
movie : 83516
movies : 15434
mr : 2673
much : 18898
music : 6188
must : 6161
my : 24053
name : 3084
need : 3516
never : 12831
new : 7959
next : 3323
nice : 3743
night : 3947
no : 24186
not : 59511
nothing : 8142
now : 8392
of : 288070
off : 10864
often : 3048
oh : 2525
old : 7753
on : 66296
once : 4387
one : 50374
only : 22994
or : 34908
original : 6179
other : 17776
others : 3185
our : 4955
out : 32700
over : 10609
own : 6474
part : 7603
parts : 2344
past : 2345
people : 17484
perfect : 3030
performance : 5416
performances : 3391
perhaps : 3110
person : 3016
picture : 2772
piece : 2966
place : 4508
play : 4332
played : 5083
playing : 3117
plays : 4336
plot : 12310
point : 5894
poor : 3715
pretty : 7159
probably : 5538
problem : 2739
production : 3377
put : 4661
quality : 2458
quite : 7212
rather : 5242
read : 3716
real : 9003
really : 22894
reason : 4409
recommend : 3387
remember : 3262
rest : 3431
right : 6202
role : 6046
said : 4240
same : 8003
saw : 6286
say : 10618
scene : 10527
scenes : 10171
school : 3227
screen : 4386
script : 5658
second : 3539
see : 22434
seeing : 4082
seem : 4211
seemed : 2700
seems : 7041
seen : 13053
sense : 4416
series : 6103
set : 4366
several : 2822
sex : 3174
she : 23804
shes : 2707
short : 3635
shot : 3878
should : 9562
show : 12023
shows : 4840
side : 2341
simply : 3817
since : 5570
small : 3036
so : 38547
some : 30640
someone : 4342
something : 9774
son : 2348
sort : 2878
sound : 2714
special : 4101
star : 3527
stars : 2914
start : 3335
still : 10598
story : 22047
stupid : 3342
style : 2813
such : 9888
supposed : 2848
sure : 5106
take : 6831
takes : 4210
tell : 3320
terrible : 3198
than : 19168
that : 135821
thats : 7202
the : 650656
their : 22655
them : 15345
then : 15353
there : 29160
theres : 5851
these : 10556
they : 41346
theyre : 2446
thing : 8902
things : 7179
think : 14189
this : 145449
those : 9276
though : 8340
thought : 6644
three : 4384
through : 9484
throughout : 2562
time : 23270
times : 6090
title : 2767
to : 266288
together : 4251
too : 14768
top : 3009
totally : 2720
tries : 2414
true : 4338
truly : 3425
try : 3505
trying : 4858
turn : 2572
turns : 2401
tv : 5315
two : 12922
under : 2466
understand : 3263
unfortunately : 2372
until : 3447
up : 24221
us : 7662
use : 3527
used : 3781
version : 3996
very : 27488
video : 3092
want : 7257
wanted : 2699
wants : 2529
war : 4022
was : 95186
wasnt : 4489
waste : 2756
watch : 13429
watched : 4455
watching : 8921
way : 14996
we : 18790
well : 18456
went : 2998
were : 22169
what : 29447
when : 27390
where : 12326
which : 22986
while : 9817
white : 2539
who : 40133
whole : 6067
why : 10067
wife : 3708
will : 17969
with : 86552
without : 6327
woman : 4904
women : 3288
wonderful : 3151
wont : 2631
work : 7996
works : 2408
world : 6789
worse : 2781
worst : 5223
worth : 4579
would : 24001
writing : 2430
written : 2793
wrong : 3369
year : 3476
years : 8649
yes : 2686
yet : 5247
you : 59171
youll : 2602
young : 6910
your : 11369
youre : 3810

In [40]:
# Problem 5

# Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary

| Range | Output              |
| ----- | ------------------- |
| (1,1) | Unigrams only       |
| (1,2) | Unigrams + Bigrams  |
| (2,2) | Bigrams only        |
| (3,3) | Trigrams only       |
| (1,3) | Uni + Bi + Trigrams |
| (2,3) | Bi + Trigrams       |

In [43]:
cv=CountVectorizer(max_features=500, ngram_range=(1,2)) 
BoW=cv.fit_transform(df['review'])

In [42]:
print(cv.vocabulary_)

{'one of': np.int64(277), 'of the': np.int64(264), 'the other': np.int64(367), 'they are': np.int64(398), 'this is': np.int64(403), 'from the': np.int64(110), 'is not': np.int64(174), 'for the': np.int64(108), 'this show': np.int64(406), 'in the': np.int64(158), 'that is': np.int64(319), 'is the': np.int64(181), 'to the': np.int64(431), 'all the': np.int64(8), 'on the': np.int64(274), 'the main': np.int64(356), 'the show': np.int64(382), 'due to': np.int64(81), 'the fact': np.int64(348), 'fact that': np.int64(90), 'that it': np.int64(320), 'around the': np.int64(36), 'the first': np.int64(352), 'it was': np.int64(200), 'for it': np.int64(105), 'it but': np.int64(187), 'lack of': np.int64(208), 'what is': np.int64(467), 'if you': np.int64(142), 'you can': np.int64(493), 'is very': np.int64(183), 'sense of': np.int64(299), 'the entire': np.int64(347), 'the actors': np.int64(332), 'not only': np.int64(249), 'but he': np.int64(60), 'he has': np.int64(130), 'see the': np.int64(294), 'by the': np.int64(69), 'is it': np.int64(170), 'but it': np.int64(62), 'it is': np.int64(194), 'the great': np.int64(354), 'and his': np.int64(15), 'with the': np.int64(488), 'rather than': np.int64(288), 'the scenes': np.int64(377), 'and the': np.int64(25), 'of their': np.int64(265), 'this was': np.int64(407), 'way to': np.int64(462), 'the plot': np.int64(369), 'plot is': np.int64(287), 'but the': np.int64(66), 'the characters': np.int64(342), 'characters are': np.int64(72), 'even the': np.int64(87), 'may be': np.int64(223), 'when they': np.int64(474), 'is still': np.int64(179), 'many of': np.int64(222), 'was the': np.int64(455), 'the most': np.int64(358), 'in this': np.int64(160), 'not be': np.int64(247), 'be the': np.int64(52), 'of his': np.int64(258), 'to go': np.int64(417), 'in his': np.int64(149), 'movie is': np.int64(232), 'of all': np.int64(253), 'going to': np.int64(116), 'to make': np.int64(425), 'the movie': np.int64(359), 'and then': np.int64(26), 'we have': np.int64(464), 'with his': np.int64(486), 'the film': np.int64(349), 'to see': np.int64(428), 'movie and': np.int64(228), 'with some': np.int64(487), 'out of': np.int64(279), 'of 10': np.int64(252), 'the time': np.int64(384), 'film to': np.int64(99), 'to watch': np.int64(433), 'movie that': np.int64(234), 'seems to': np.int64(297), 'to be': np.int64(412), 'about the': np.int64(2), 'the same': np.int64(375), 'the director': np.int64(343), 'the action': np.int64(331), 'one is': np.int64(276), 'in one': np.int64(154), 'the next': np.int64(362), 'no one': np.int64(246), 'to know': np.int64(424), 'film has': np.int64(94), 'we are': np.int64(463), 'the world': np.int64(392), 'in their': np.int64(159), 'the best': np.int64(336), 'in which': np.int64(161), 'most of': np.int64(227), 'the people': np.int64(368), 'acting is': np.int64(4), 'is good': np.int64(167), 'the rest': np.int64(372), 'rest of': np.int64(290), 'for his': np.int64(104), 'story of': np.int64(312), 'but its': np.int64(63), 'its not': np.int64(203), 'it just': np.int64(195), 'the last': np.int64(355), 'of her': np.int64(257), 'but that': np.int64(65), 'for this': np.int64(109), 'this movie': np.int64(404), 'like to': np.int64(212), 'they have': np.int64(399), 'it would': np.int64(201), 'and this': np.int64(29), 'the way': np.int64(390), 'like this': np.int64(211), 'would be': np.int64(490), 'out to': np.int64(281), 'and have': np.int64(12), 'me to': np.int64(224), 'is so': np.int64(178), 'when it': np.int64(472), 'was not': np.int64(453), 'and its': np.int64(19), 'waste of': np.int64(457), 'of time': np.int64(270), 'hard to': np.int64(121), 'that the': np.int64(323), 'the original': np.int64(366), 'as it': np.int64(40), 'is just': np.int64(171), 'about this': np.int64(3), 'this film': np.int64(402), 'watching this': np.int64(461), 'ive seen': np.int64(205), 'the worst': np.int64(393), 'of them': np.int64(266), 'the films': np.int64(350), 'and is': np.int64(17), 'have been': np.int64(125), 'the end': np.int64(345), 'of film': np.int64(256), 'film the': np.int64(98), 'the only': np.int64(365), 'at least': np.int64(46), 'bit of': np.int64(58), 'of an': np.int64(254), 'you will': np.int64(499), 'you are': np.int64(492), 'is one': np.int64(175), 'of those': np.int64(269), 'where the': np.int64(476), 'was very': np.int64(456), 'as the': np.int64(42), 'there were': np.int64(397), 'who is': np.int64(481), 'saw this': np.int64(291), 'the big': np.int64(337), 'might be': np.int64(225), 'when the': np.int64(473), 'up and': np.int64(438), 'up the': np.int64(440), 'the story': np.int64(383), 'make it': np.int64(219), 'up to': np.int64(441), 'and not': np.int64(20), 'there are': np.int64(394), 'im not': np.int64(144), 'fan of': np.int64(91), 'people who': np.int64(284), 'should be': np.int64(302), 'that this': np.int64(326), 'along with': np.int64(9), 'played by': np.int64(286), 'is pretty': np.int64(176), 'the whole': np.int64(391), 'know what': np.int64(207), 'when he': np.int64(471), 'he was': np.int64(132), 'film is': np.int64(96), 'we see': np.int64(465), 'as they': np.int64(43), 'for some': np.int64(107), 'see this': np.int64(295), 'of it': np.int64(259), 'that would': np.int64(328), 'such as': np.int64(313), 'the scene': np.int64(376), 'the cast': np.int64(340), 'trying to': np.int64(437), 'because the': np.int64(55), 'my favorite': np.int64(243), 'do not': np.int64(77), 'is that': np.int64(180), 'to do': np.int64(413), 'have to': np.int64(129), 'to keep': np.int64(422), 'say that': np.int64(292), 'does not': np.int64(79), 'but this': np.int64(68), 'the man': np.int64(357), 'movie to': np.int64(236), 'kind of': np.int64(206), 'ive ever': np.int64(204), 'ever seen': np.int64(89), 'sort of': np.int64(308), 'what was': np.int64(470), 'in that': np.int64(157), 'to get': np.int64(415), 'with this': np.int64(489), 'this one': np.int64(405), 'lots of': np.int64(217), 'could have': np.int64(74), 'film but': np.int64(93), 'as he': np.int64(38), 'up with': np.int64(442), 'did not': np.int64(76), 'the right': np.int64(373), 'the character': np.int64(341), 'in its': np.int64(151), 'some of': np.int64(307), 'film in': np.int64(95), 'special effects': np.int64(309), 'much more': np.int64(240), 'of my': np.int64(261), 'there was': np.int64(396), 'they were': np.int64(400), 'wanted to': np.int64(448), 'at the': np.int64(47), 'the final': np.int64(351), 'the old': np.int64(363), 'the beginning': np.int64(335), 'time and': np.int64(411), 'if it': np.int64(139), 'much of': np.int64(241), 'to say': np.int64(427), 'to find': np.int64(414), 'has been': np.int64(122), 'which is': np.int64(477), 'have seen': np.int64(127), 'like it': np.int64(209), 'must have': np.int64(242), 'if the': np.int64(140), 'of this': np.int64(268), 'would have': np.int64(491), 'couple of': np.int64(75), 'film with': np.int64(101), 'after the': np.int64(5), 'those who': np.int64(408), 'who are': np.int64(479), 'in all': np.int64(145), 'full of': np.int64(111), 'to her': np.int64(419), 'go to': np.int64(115), 'if youre': np.int64(143), 'looking for': np.int64(214), 'the one': np.int64(364), 'had the': np.int64(119), 'because it': np.int64(53), 'movie the': np.int64(235), 'story is': np.int64(311), 'at all': np.int64(45), 'all of': np.int64(6), 'it has': np.int64(192), 'are so': np.int64(34), 'supposed to': np.int64(314), 'in it': np.int64(150), 'try to': np.int64(436), 'and they': np.int64(28), 'you have': np.int64(495), 'to kill': np.int64(423), 'watch it': np.int64(458), 'too much': np.int64(434), 'on his': np.int64(273), 'it the': np.int64(198), 'the music': np.int64(361), 'used to': np.int64(443), 'like the': np.int64(210), 'it seems': np.int64(197), 'on this': np.int64(275), 'in fact': np.int64(147), 'bunch of': np.int64(59), 'to take': np.int64(430), 'the dvd': np.int64(344), 'to show': np.int64(429), 'to give': np.int64(416), 'and it': np.int64(18), 'based on': np.int64(51), 'much better': np.int64(239), 'than the': np.int64(315), 'the acting': np.int64(330), 'there is': np.int64(395), 'is no': np.int64(173), 'to me': np.int64(426), 'not even': np.int64(248), 'she is': np.int64(300), 'think that': np.int64(401), 'the role': np.int64(374), 'movie was': np.int64(237), 'the top': np.int64(386), 'is an': np.int64(166), 'of what': np.int64(271), 'can be': np.int64(70), 'characters and': np.int64(71), 'is to': np.int64(182), 'the point': np.int64(370), 'it and': np.int64(185), 'more than': np.int64(226), 'into the': np.int64(163), 'how the': np.int64(137), 'looks like': np.int64(215), 'wants to': np.int64(449), 'you see': np.int64(497), 'what it': np.int64(468), 'film was': np.int64(100), 'movie with': np.int64(238), 'to have': np.int64(418), 'was just': np.int64(451), 'lot of': np.int64(216), 'will be': np.int64(483), 'it in': np.int64(193), 'was so': np.int64(454), 'and was': np.int64(30), 'able to': np.int64(0), 'so much': np.int64(306), 'need to': np.int64(245), 'who was': np.int64(482), 'had to': np.int64(120), 'of its': np.int64(260), 'that has': np.int64(317), 'so many': np.int64(305), 'is about': np.int64(164), 'the audience': np.int64(333), 'and even': np.int64(11), 'at times': np.int64(48), 'as an': np.int64(37), 'end of': np.int64(84), 'of people': np.int64(262), 'the second': np.int64(380), 'who has': np.int64(480), 'that he': np.int64(318), 'while the': np.int64(478), 'even though': np.int64(88), 'his own': np.int64(135), 'him to': np.int64(134), 'he is': np.int64(131), 'part of': np.int64(283), 'in an': np.int64(146), 'when you': np.int64(475), 'man who': np.int64(221), 'it does': np.int64(188), 'is also': np.int64(165), 'between the': np.int64(57), 'and in': np.int64(16), 'seen in': np.int64(298), 'out the': np.int64(280), 'film that': np.int64(97), 'of that': np.int64(263), 'during the': np.int64(82), 'and you': np.int64(31), 'you know': np.int64(496), 'movie has': np.int64(230), 'about it': np.int64(1), 'that its': np.int64(321), 'its just': np.int64(202), 'movie but': np.int64(229), 'watch this': np.int64(460), 'because of': np.int64(54), 'is in': np.int64(169), 'in her': np.int64(148), 'version of': np.int64(444), 'but they': np.int64(67), 'but not': np.int64(64), 'to this': np.int64(432), 'has to': np.int64(124), 'movie it': np.int64(233), 'watch the': np.int64(459), 'that are': np.int64(316), 'or the': np.int64(278), 'throughout the': np.int64(410), 'of course': np.int64(255), 'see it': np.int64(293), 'made me': np.int64(218), 'the camera': np.int64(339), 'it had': np.int64(191), 'the script': np.int64(379), 'the good': np.int64(353), 'recommend this': np.int64(289), 'the book': np.int64(338), 'up in': np.int64(439), 'the two': np.int64(387), 'the ending': np.int64(346), 'off the': np.int64(272), 'are not': np.int64(33), 'not to': np.int64(251), 'with an': np.int64(484), 'get to': np.int64(113), 'each other': np.int64(83), 'for me': np.int64(106), 'have the': np.int64(128), 'and that': np.int64(24), 'but in': np.int64(61), 'as well': np.int64(44), 'well as': np.int64(466), 'in my': np.int64(153), 'my opinion': np.int64(244), 'through the': np.int64(409), 'could be': np.int64(73), 'and all': np.int64(10), 'all that': np.int64(7), 'not the': np.int64(250), 'his wife': np.int64(136), 'and he': np.int64(13), 'enough to': np.int64(85), 'away from': np.int64(49), 'make the': np.int64(220), 'and some': np.int64(23), 'instead of': np.int64(162), 'the movies': np.int64(360), 'over the': np.int64(282), 'in love': np.int64(152), 'him and': np.int64(133), 'with her': np.int64(485), 'to his': np.int64(420), 'back to': np.int64(50), 'it all': np.int64(184), 'of these': np.int64(267), 'as much': np.int64(41), 'better than': np.int64(56), 'story and': np.int64(310), 'the screen': np.int64(378), 'the viewer': np.int64(389), 'was made': np.int64(452), 'it to': np.int64(199), 'group of': np.int64(117), 'want to': np.int64(447), 'it doesnt': np.int64(189), 'for her': np.int64(103), 'that was': np.int64(327), 'is really': np.int64(177), 'that there': np.int64(324), 'you want': np.int64(498), 'that she': np.int64(322), 'in some': np.int64(156), 'is more': np.int64(172), 'piece of': np.int64(285), 'the title': np.int64(385), 'that they': np.int64(325), 'how to': np.int64(138), 'give it': np.int64(114), 'it for': np.int64(190), 'tries to': np.int64(435), 'even if': np.int64(86), 'has the': np.int64(123), 'the real': np.int64(371), 'she was': np.int64(301), 'the very': np.int64(388), 'are the': np.int64(35), 'seem to': np.int64(296), 'that you': np.int64(329), 'so bad': np.int64(304), 'get the': np.int64(112), 'and there': np.int64(27), 'what the': np.int64(469), 'have ever': np.int64(126), 'dont know': np.int64(80), 'you dont': np.int64(494), 'to it': np.int64(421), 'any of': np.int64(32), 'film and': np.int64(92), 'if they': np.int64(141), 'and her': np.int64(14), 'do with': np.int64(78), 'look at': np.int64(213), 'very good': np.int64(445), 'as if': np.int64(39), 'should have': np.int64(303), 'and so': np.int64(22), 'is great': np.int64(168), 'the bad': np.int64(334), 'movie in': np.int64(231), 'had been': np.int64(118), 'it as': np.int64(186), 'in order': np.int64(155), 'very well': np.int64(446), 'was in': np.int64(450), 'first time': np.int64(102), 'and she': np.int64(21), 'the series': np.int64(381), 'it on': np.int64(196)}

In [44]:
cv=CountVectorizer(max_features=500, ngram_range=(2,2)) 
BoW=cv.fit_transform(df['review'])
print(cv.vocabulary_)

{'one of': np.int64(277), 'of the': np.int64(264), 'the other': np.int64(367), 'they are': np.int64(398), 'this is': np.int64(403), 'from the': np.int64(110), 'is not': np.int64(174), 'for the': np.int64(108), 'this show': np.int64(406), 'in the': np.int64(158), 'that is': np.int64(319), 'is the': np.int64(181), 'to the': np.int64(431), 'all the': np.int64(8), 'on the': np.int64(274), 'the main': np.int64(356), 'the show': np.int64(382), 'due to': np.int64(81), 'the fact': np.int64(348), 'fact that': np.int64(90), 'that it': np.int64(320), 'around the': np.int64(36), 'the first': np.int64(352), 'it was': np.int64(200), 'for it': np.int64(105), 'it but': np.int64(187), 'lack of': np.int64(208), 'what is': np.int64(467), 'if you': np.int64(142), 'you can': np.int64(493), 'is very': np.int64(183), 'sense of': np.int64(299), 'the entire': np.int64(347), 'the actors': np.int64(332), 'not only': np.int64(249), 'but he': np.int64(60), 'he has': np.int64(130), 'see the': np.int64(294), 'by the': np.int64(69), 'is it': np.int64(170), 'but it': np.int64(62), 'it is': np.int64(194), 'the great': np.int64(354), 'and his': np.int64(15), 'with the': np.int64(488), 'rather than': np.int64(288), 'the scenes': np.int64(377), 'and the': np.int64(25), 'of their': np.int64(265), 'this was': np.int64(407), 'way to': np.int64(462), 'the plot': np.int64(369), 'plot is': np.int64(287), 'but the': np.int64(66), 'the characters': np.int64(342), 'characters are': np.int64(72), 'even the': np.int64(87), 'may be': np.int64(223), 'when they': np.int64(474), 'is still': np.int64(179), 'many of': np.int64(222), 'was the': np.int64(455), 'the most': np.int64(358), 'in this': np.int64(160), 'not be': np.int64(247), 'be the': np.int64(52), 'of his': np.int64(258), 'to go': np.int64(417), 'in his': np.int64(149), 'movie is': np.int64(232), 'of all': np.int64(253), 'going to': np.int64(116), 'to make': np.int64(425), 'the movie': np.int64(359), 'and then': np.int64(26), 'we have': np.int64(464), 'with his': np.int64(486), 'the film': np.int64(349), 'to see': np.int64(428), 'movie and': np.int64(228), 'with some': np.int64(487), 'out of': np.int64(279), 'of 10': np.int64(252), 'the time': np.int64(384), 'film to': np.int64(99), 'to watch': np.int64(433), 'movie that': np.int64(234), 'seems to': np.int64(297), 'to be': np.int64(412), 'about the': np.int64(2), 'the same': np.int64(375), 'the director': np.int64(343), 'the action': np.int64(331), 'one is': np.int64(276), 'in one': np.int64(154), 'the next': np.int64(362), 'no one': np.int64(246), 'to know': np.int64(424), 'film has': np.int64(94), 'we are': np.int64(463), 'the world': np.int64(392), 'in their': np.int64(159), 'the best': np.int64(336), 'in which': np.int64(161), 'most of': np.int64(227), 'the people': np.int64(368), 'acting is': np.int64(4), 'is good': np.int64(167), 'the rest': np.int64(372), 'rest of': np.int64(290), 'for his': np.int64(104), 'story of': np.int64(312), 'but its': np.int64(63), 'its not': np.int64(203), 'it just': np.int64(195), 'the last': np.int64(355), 'of her': np.int64(257), 'but that': np.int64(65), 'for this': np.int64(109), 'this movie': np.int64(404), 'like to': np.int64(212), 'they have': np.int64(399), 'it would': np.int64(201), 'and this': np.int64(29), 'the way': np.int64(390), 'like this': np.int64(211), 'would be': np.int64(490), 'out to': np.int64(281), 'and have': np.int64(12), 'me to': np.int64(224), 'is so': np.int64(178), 'when it': np.int64(472), 'was not': np.int64(453), 'and its': np.int64(19), 'waste of': np.int64(457), 'of time': np.int64(270), 'hard to': np.int64(121), 'that the': np.int64(323), 'the original': np.int64(366), 'as it': np.int64(40), 'is just': np.int64(171), 'about this': np.int64(3), 'this film': np.int64(402), 'watching this': np.int64(461), 'ive seen': np.int64(205), 'the worst': np.int64(393), 'of them': np.int64(266), 'the films': np.int64(350), 'and is': np.int64(17), 'have been': np.int64(125), 'the end': np.int64(345), 'of film': np.int64(256), 'film the': np.int64(98), 'the only': np.int64(365), 'at least': np.int64(46), 'bit of': np.int64(58), 'of an': np.int64(254), 'you will': np.int64(499), 'you are': np.int64(492), 'is one': np.int64(175), 'of those': np.int64(269), 'where the': np.int64(476), 'was very': np.int64(456), 'as the': np.int64(42), 'there were': np.int64(397), 'who is': np.int64(481), 'saw this': np.int64(291), 'the big': np.int64(337), 'might be': np.int64(225), 'when the': np.int64(473), 'up and': np.int64(438), 'up the': np.int64(440), 'the story': np.int64(383), 'make it': np.int64(219), 'up to': np.int64(441), 'and not': np.int64(20), 'there are': np.int64(394), 'im not': np.int64(144), 'fan of': np.int64(91), 'people who': np.int64(284), 'should be': np.int64(302), 'that this': np.int64(326), 'along with': np.int64(9), 'played by': np.int64(286), 'is pretty': np.int64(176), 'the whole': np.int64(391), 'know what': np.int64(207), 'when he': np.int64(471), 'he was': np.int64(132), 'film is': np.int64(96), 'we see': np.int64(465), 'as they': np.int64(43), 'for some': np.int64(107), 'see this': np.int64(295), 'of it': np.int64(259), 'that would': np.int64(328), 'such as': np.int64(313), 'the scene': np.int64(376), 'the cast': np.int64(340), 'trying to': np.int64(437), 'because the': np.int64(55), 'my favorite': np.int64(243), 'do not': np.int64(77), 'is that': np.int64(180), 'to do': np.int64(413), 'have to': np.int64(129), 'to keep': np.int64(422), 'say that': np.int64(292), 'does not': np.int64(79), 'but this': np.int64(68), 'the man': np.int64(357), 'movie to': np.int64(236), 'kind of': np.int64(206), 'ive ever': np.int64(204), 'ever seen': np.int64(89), 'sort of': np.int64(308), 'what was': np.int64(470), 'in that': np.int64(157), 'to get': np.int64(415), 'with this': np.int64(489), 'this one': np.int64(405), 'lots of': np.int64(217), 'could have': np.int64(74), 'film but': np.int64(93), 'as he': np.int64(38), 'up with': np.int64(442), 'did not': np.int64(76), 'the right': np.int64(373), 'the character': np.int64(341), 'in its': np.int64(151), 'some of': np.int64(307), 'film in': np.int64(95), 'special effects': np.int64(309), 'much more': np.int64(240), 'of my': np.int64(261), 'there was': np.int64(396), 'they were': np.int64(400), 'wanted to': np.int64(448), 'at the': np.int64(47), 'the final': np.int64(351), 'the old': np.int64(363), 'the beginning': np.int64(335), 'time and': np.int64(411), 'if it': np.int64(139), 'much of': np.int64(241), 'to say': np.int64(427), 'to find': np.int64(414), 'has been': np.int64(122), 'which is': np.int64(477), 'have seen': np.int64(127), 'like it': np.int64(209), 'must have': np.int64(242), 'if the': np.int64(140), 'of this': np.int64(268), 'would have': np.int64(491), 'couple of': np.int64(75), 'film with': np.int64(101), 'after the': np.int64(5), 'those who': np.int64(408), 'who are': np.int64(479), 'in all': np.int64(145), 'full of': np.int64(111), 'to her': np.int64(419), 'go to': np.int64(115), 'if youre': np.int64(143), 'looking for': np.int64(214), 'the one': np.int64(364), 'had the': np.int64(119), 'because it': np.int64(53), 'movie the': np.int64(235), 'story is': np.int64(311), 'at all': np.int64(45), 'all of': np.int64(6), 'it has': np.int64(192), 'are so': np.int64(34), 'supposed to': np.int64(314), 'in it': np.int64(150), 'try to': np.int64(436), 'and they': np.int64(28), 'you have': np.int64(495), 'to kill': np.int64(423), 'watch it': np.int64(458), 'too much': np.int64(434), 'on his': np.int64(273), 'it the': np.int64(198), 'the music': np.int64(361), 'used to': np.int64(443), 'like the': np.int64(210), 'it seems': np.int64(197), 'on this': np.int64(275), 'in fact': np.int64(147), 'bunch of': np.int64(59), 'to take': np.int64(430), 'the dvd': np.int64(344), 'to show': np.int64(429), 'to give': np.int64(416), 'and it': np.int64(18), 'based on': np.int64(51), 'much better': np.int64(239), 'than the': np.int64(315), 'the acting': np.int64(330), 'there is': np.int64(395), 'is no': np.int64(173), 'to me': np.int64(426), 'not even': np.int64(248), 'she is': np.int64(300), 'think that': np.int64(401), 'the role': np.int64(374), 'movie was': np.int64(237), 'the top': np.int64(386), 'is an': np.int64(166), 'of what': np.int64(271), 'can be': np.int64(70), 'characters and': np.int64(71), 'is to': np.int64(182), 'the point': np.int64(370), 'it and': np.int64(185), 'more than': np.int64(226), 'into the': np.int64(163), 'how the': np.int64(137), 'looks like': np.int64(215), 'wants to': np.int64(449), 'you see': np.int64(497), 'what it': np.int64(468), 'film was': np.int64(100), 'movie with': np.int64(238), 'to have': np.int64(418), 'was just': np.int64(451), 'lot of': np.int64(216), 'will be': np.int64(483), 'it in': np.int64(193), 'was so': np.int64(454), 'and was': np.int64(30), 'able to': np.int64(0), 'so much': np.int64(306), 'need to': np.int64(245), 'who was': np.int64(482), 'had to': np.int64(120), 'of its': np.int64(260), 'that has': np.int64(317), 'so many': np.int64(305), 'is about': np.int64(164), 'the audience': np.int64(333), 'and even': np.int64(11), 'at times': np.int64(48), 'as an': np.int64(37), 'end of': np.int64(84), 'of people': np.int64(262), 'the second': np.int64(380), 'who has': np.int64(480), 'that he': np.int64(318), 'while the': np.int64(478), 'even though': np.int64(88), 'his own': np.int64(135), 'him to': np.int64(134), 'he is': np.int64(131), 'part of': np.int64(283), 'in an': np.int64(146), 'when you': np.int64(475), 'man who': np.int64(221), 'it does': np.int64(188), 'is also': np.int64(165), 'between the': np.int64(57), 'and in': np.int64(16), 'seen in': np.int64(298), 'out the': np.int64(280), 'film that': np.int64(97), 'of that': np.int64(263), 'during the': np.int64(82), 'and you': np.int64(31), 'you know': np.int64(496), 'movie has': np.int64(230), 'about it': np.int64(1), 'that its': np.int64(321), 'its just': np.int64(202), 'movie but': np.int64(229), 'watch this': np.int64(460), 'because of': np.int64(54), 'is in': np.int64(169), 'in her': np.int64(148), 'version of': np.int64(444), 'but they': np.int64(67), 'but not': np.int64(64), 'to this': np.int64(432), 'has to': np.int64(124), 'movie it': np.int64(233), 'watch the': np.int64(459), 'that are': np.int64(316), 'or the': np.int64(278), 'throughout the': np.int64(410), 'of course': np.int64(255), 'see it': np.int64(293), 'made me': np.int64(218), 'the camera': np.int64(339), 'it had': np.int64(191), 'the script': np.int64(379), 'the good': np.int64(353), 'recommend this': np.int64(289), 'the book': np.int64(338), 'up in': np.int64(439), 'the two': np.int64(387), 'the ending': np.int64(346), 'off the': np.int64(272), 'are not': np.int64(33), 'not to': np.int64(251), 'with an': np.int64(484), 'get to': np.int64(113), 'each other': np.int64(83), 'for me': np.int64(106), 'have the': np.int64(128), 'and that': np.int64(24), 'but in': np.int64(61), 'as well': np.int64(44), 'well as': np.int64(466), 'in my': np.int64(153), 'my opinion': np.int64(244), 'through the': np.int64(409), 'could be': np.int64(73), 'and all': np.int64(10), 'all that': np.int64(7), 'not the': np.int64(250), 'his wife': np.int64(136), 'and he': np.int64(13), 'enough to': np.int64(85), 'away from': np.int64(49), 'make the': np.int64(220), 'and some': np.int64(23), 'instead of': np.int64(162), 'the movies': np.int64(360), 'over the': np.int64(282), 'in love': np.int64(152), 'him and': np.int64(133), 'with her': np.int64(485), 'to his': np.int64(420), 'back to': np.int64(50), 'it all': np.int64(184), 'of these': np.int64(267), 'as much': np.int64(41), 'better than': np.int64(56), 'story and': np.int64(310), 'the screen': np.int64(378), 'the viewer': np.int64(389), 'was made': np.int64(452), 'it to': np.int64(199), 'group of': np.int64(117), 'want to': np.int64(447), 'it doesnt': np.int64(189), 'for her': np.int64(103), 'that was': np.int64(327), 'is really': np.int64(177), 'that there': np.int64(324), 'you want': np.int64(498), 'that she': np.int64(322), 'in some': np.int64(156), 'is more': np.int64(172), 'piece of': np.int64(285), 'the title': np.int64(385), 'that they': np.int64(325), 'how to': np.int64(138), 'give it': np.int64(114), 'it for': np.int64(190), 'tries to': np.int64(435), 'even if': np.int64(86), 'has the': np.int64(123), 'the real': np.int64(371), 'she was': np.int64(301), 'the very': np.int64(388), 'are the': np.int64(35), 'seem to': np.int64(296), 'that you': np.int64(329), 'so bad': np.int64(304), 'get the': np.int64(112), 'and there': np.int64(27), 'what the': np.int64(469), 'have ever': np.int64(126), 'dont know': np.int64(80), 'you dont': np.int64(494), 'to it': np.int64(421), 'any of': np.int64(32), 'film and': np.int64(92), 'if they': np.int64(141), 'and her': np.int64(14), 'do with': np.int64(78), 'look at': np.int64(213), 'very good': np.int64(445), 'as if': np.int64(39), 'should have': np.int64(303), 'and so': np.int64(22), 'is great': np.int64(168), 'the bad': np.int64(334), 'movie in': np.int64(231), 'had been': np.int64(118), 'it as': np.int64(186), 'in order': np.int64(155), 'very well': np.int64(446), 'was in': np.int64(450), 'first time': np.int64(102), 'and she': np.int64(21), 'the series': np.int64(381), 'it on': np.int64(196)}

In [45]:
cv=CountVectorizer(max_features=500, ngram_range=(3,3)) 
BoW=cv.fit_transform(df['review'])
print(cv.vocabulary_)

{'one of the': np.int64(252), 'of the other': np.int64(234), 'this is not': np.int64(409), 'that is the': np.int64(293), 'of the show': np.int64(239), 'due to the': np.int64(79), 'the fact that': np.int64(325), 'fact that it': np.int64(81), 'if you can': np.int64(109), 'the actors are': np.int64(308), 'but it is': np.int64(63), 'of the great': np.int64(228), 'the plot is': np.int64(366), 'the characters are': np.int64(316), 'thought it was': np.int64(431), 'may not be': np.int64(195), 'but it was': np.int64(64), 'first of all': np.int64(88), 'the movie is': np.int64(354), 'in real life': np.int64(123), 'out of 10': np.int64(258), 'as for the': np.int64(33), 'seems to be': np.int64(280), 'the film has': np.int64(329), 'to see how': np.int64(451), 'most of the': np.int64(199), 'the rest of': np.int64(370), 'rest of the': np.int64(270), 'in the last': np.int64(131), 'in one of': np.int64(121), 'fun to watch': np.int64(96), 'in the world': np.int64(139), 'for this movie': np.int64(93), 'would like to': np.int64(494), 'black and white': np.int64(60), 'by the way': np.int64(72), 'out to be': np.int64(260), 'to be in': np.int64(435), 'waste of time': np.int64(480), 'to believe that': np.int64(438), 'as it is': np.int64(35), 'about this film': np.int64(2), 'and this is': np.int64(28), 'of the worst': np.int64(244), 'to see the': np.int64(453), 'the only thing': np.int64(362), 'only thing that': np.int64(255), 'if you like': np.int64(113), 'like this movie': np.int64(190), 'movie if you': np.int64(200), 'if you are': np.int64(108), 'is one of': np.int64(150), 'one of those': np.int64(254), 'it was very': np.int64(182), 'saw this movie': np.int64(272), 'out of the': np.int64(259), 'in the end': np.int64(128), 'in the film': np.int64(129), 'there are no': np.int64(391), 'big fan of': np.int64(59), 'the only one': np.int64(360), 'that this is': np.int64(303), 'in the movie': np.int64(133), 'in this movie': np.int64(142), 'this movie is': np.int64(421), 'in this film': np.int64(141), 'this film is': np.int64(401), 'for some reason': np.int64(89), 'see this movie': np.int64(276), 'of the film': np.int64(225), 'is trying to': np.int64(161), 'say that this': np.int64(273), 'that this movie': np.int64(304), 'this movie as': np.int64(415), 'of the actors': np.int64(221), 'about the movie': np.int64(1), 'movie is the': np.int64(203), 'this movie to': np.int64(425), 'was one of': np.int64(478), 'of the most': np.int64(231), 'ive ever seen': np.int64(187), 'could have been': np.int64(74), 'this is one': np.int64(410), 'one of them': np.int64(253), 'it is not': np.int64(169), 'of the same': np.int64(236), 'of the cast': np.int64(223), 'up with the': np.int64(470), 'the character of': np.int64(314), 'is that it': np.int64(154), 'some of the': np.int64(285), 'one of my': np.int64(251), 'there was no': np.int64(395), 'at the end': np.int64(44), 'in the beginning': np.int64(125), 'if it was': np.int64(107), 'to say the': np.int64(450), 'the first film': np.int64(335), 'must have been': np.int64(207), 'the story of': np.int64(378), 'story of the': np.int64(288), 'of the first': np.int64(227), 'come up with': np.int64(73), 'all in all': np.int64(4), 'the film as': np.int64(327), 'of all the': np.int64(215), 'have to say': np.int64(106), 'to be the': np.int64(437), 'of all time': np.int64(216), 'the story is': np.int64(377), 'all of the': np.int64(5), 'is supposed to': np.int64(153), 'supposed to be': np.int64(290), 'towards the end': np.int64(466), 'but this is': np.int64(66), 'this is just': np.int64(408), 'if you have': np.int64(111), 'all the time': np.int64(7), 'going to be': np.int64(99), 'this is the': np.int64(411), 'is the only': np.int64(159), 'at the same': np.int64(45), 'the same time': np.int64(372), 'this was the': np.int64(430), 'the worst movie': np.int64(387), 'based on the': np.int64(50), 'the acting is': np.int64(306), 'movie is so': np.int64(202), 'the main character': np.int64(347), 'there is no': np.int64(393), 'to the story': np.int64(461), 'back in the': np.int64(48), 'this movie was': np.int64(426), 'is the best': np.int64(156), 'the film was': np.int64(334), 'this film was': np.int64(405), 'on and on': np.int64(247), 'the lack of': np.int64(344), 'be able to': np.int64(51), 'that it is': np.int64(294), 'movie is not': np.int64(201), 'turns out to': np.int64(467), 'seems to have': np.int64(281), 'in the past': np.int64(135), 'the film but': np.int64(328), 'end of the': np.int64(80), 'the lives of': np.int64(346), 'have been better': np.int64(102), 'this one is': np.int64(427), 'is the most': np.int64(158), 'the film is': np.int64(330), 'of the best': np.int64(222), 'fact that the': np.int64(82), 'that the film': np.int64(297), 'in which the': np.int64(144), 'the whole thing': np.int64(385), 'the movie was': np.int64(357), 'the entire film': np.int64(323), 'you have to': np.int64(497), 'to the end': np.int64(457), 'the beginning of': np.int64(310), 'at one point': np.int64(42), 'the first half': np.int64(336), 'half of the': np.int64(100), 'this movie has': np.int64(419), 'of the movie': np.int64(232), 'the movie but': np.int64(352), 'as far as': np.int64(32), 'the only reason': np.int64(361), 'to watch this': np.int64(465), 'the idea of': np.int64(342), 'was going to': np.int64(476), 'or at least': np.int64(256), 'this movie because': np.int64(416), 'at the beginning': np.int64(43), 'because of the': np.int64(55), 'the main characters': np.int64(348), 'to this movie': np.int64(462), 'the death of': np.int64(319), 'the end the': np.int64(321), 'of the films': np.int64(226), 'in the way': np.int64(138), 'in front of': np.int64(117), 'of the greatest': np.int64(229), 'throughout the film': np.int64(432), 'the end of': np.int64(320), 'recommend this movie': np.int64(268), 'is based on': np.int64(145), 'between the two': np.int64(58), 'the ending is': np.int64(322), 'for those who': np.int64(94), 'to be one': np.int64(436), 'be one of': np.int64(52), 'nothing more than': np.int64(213), 'was supposed to': np.int64(479), 'to see this': np.int64(454), 'this movie on': np.int64(423), 'parts of the': np.int64(264), 'as well as': np.int64(41), 'well as the': np.int64(486), 'of course the': np.int64(217), 'the movie the': np.int64(356), 'the whole movie': np.int64(384), 'in my opinion': np.int64(119), 'of the characters': np.int64(224), 'the life of': np.int64(345), 'the movie and': np.int64(351), 'see this film': np.int64(275), 'have no idea': np.int64(104), 'would have been': np.int64(493), 'and of course': np.int64(16), 'is not the': np.int64(149), 'film is not': np.int64(85), 'the use of': np.int64(381), 'in love with': np.int64(118), 'that he was': np.int64(292), 'up in the': np.int64(468), 'in new york': np.int64(120), 'this movie the': np.int64(424), 'as much as': np.int64(38), 'it to be': np.int64(175), 'not going to': np.int64(210), 'to be an': np.int64(434), 'the whole film': np.int64(383), 'all the way': np.int64(8), 'dont want to': np.int64(77), 'of my life': np.int64(219), 'of the two': np.int64(242), 'the characters and': np.int64(315), 'of the time': np.int64(241), 'of this movie': np.int64(246), 'this movie but': np.int64(417), 'but there is': np.int64(65), 'to say that': np.int64(449), 'if you want': np.int64(114), 'you want to': np.int64(498), 'want to see': np.int64(472), 'that she is': np.int64(296), 'to make it': np.int64(445), 'it was not': np.int64(179), 'it could have': np.int64(164), 'the plot was': np.int64(367), 'but in the': np.int64(62), 'to see it': np.int64(452), 'the cast is': np.int64(313), 'some kind of': np.int64(284), 'by the end': np.int64(70), 'in terms of': np.int64(124), 'this film to': np.int64(404), 'the special effects': np.int64(375), 'special effects are': np.int64(287), 'this movie it': np.int64(422), 'im not sure': np.int64(115), 'the name of': np.int64(359), 'some sort of': np.int64(286), 'wanted to see': np.int64(474), 'of this film': np.int64(245), 'to have been': np.int64(443), 'for this film': np.int64(92), 'film is the': np.int64(86), 'of the original': np.int64(233), 'this film has': np.int64(400), 'about the film': np.int64(0), 'this is an': np.int64(406), 'on the other': np.int64(248), 'the other hand': np.int64(363), 'out in the': np.int64(257), 'scene in the': np.int64(274), 'and it was': np.int64(15), 'of the story': np.int64(240), 'the people who': np.int64(365), 'and in the': np.int64(13), 'may have been': np.int64(194), 'it was the': np.int64(181), 'has to be': np.int64(101), 'of one of': np.int64(220), 'it looks like': np.int64(173), 'seem to be': np.int64(277), 'that it was': np.int64(295), 'beginning of the': np.int64(56), 'fan of the': np.int64(84), 'watching this movie': np.int64(485), 'as soon as': np.int64(40), 'to find out': np.int64(440), 'this movie and': np.int64(414), 'and the story': np.int64(25), 'the story was': np.int64(379), 'is in the': np.int64(148), 'the best of': np.int64(311), 'have to be': np.int64(105), 'the worst movies': np.int64(388), 'in the book': np.int64(126), 'and there is': np.int64(27), 'over the top': np.int64(262), 'this film as': np.int64(398), 'and the acting': np.int64(21), 'have ever seen': np.int64(103), 'dont know what': np.int64(76), 'if you dont': np.int64(110), 'the first one': np.int64(338), 'none of the': np.int64(209), 'any of the': np.int64(29), 'over and over': np.int64(261), 'and over again': np.int64(18), 'all over the': np.int64(6), 'in the first': np.int64(130), 'the first movie': np.int64(337), 'this film and': np.int64(397), 'to say about': np.int64(448), 'that this film': np.int64(302), 'of the scenes': np.int64(237), 'it would be': np.int64(183), 'in the middle': np.int64(132), 'is the worst': np.int64(160), 'want to watch': np.int64(473), 'to watch the': np.int64(464), 'this piece of': np.int64(428), 'as long as': np.int64(37), 'is that the': np.int64(155), 'back to the': np.int64(49), 'by far the': np.int64(69), 'as good as': np.int64(34), 'no matter how': np.int64(208), 'what it is': np.int64(487), 'the film the': np.int64(332), 'part of the': np.int64(263), 'nothing to do': np.int64(214), 'to do with': np.int64(439), 'side of the': np.int64(283), 'much of the': np.int64(206), 'of the world': np.int64(243), 'to look at': np.int64(444), 'look at the': np.int64(191), 'the way the': np.int64(382), 'to make the': np.int64(446), 'and there are': np.int64(26), 'many of the': np.int64(193), 'is so bad': np.int64(152), 'in this one': np.int64(143), 'as one of': np.int64(39), 'there are some': np.int64(392), 'the music is': np.int64(358), 'and if you': np.int64(12), 'of the plot': np.int64(235), 'to the point': np.int64(460), 'the point of': np.int64(368), 'do with the': np.int64(75), 'the scene where': np.int64(373), 'and the other': np.int64(24), 'and it is': np.int64(14), 'to sit through': np.int64(456), 'that the movie': np.int64(298), 'the characters in': np.int64(317), 'read the book': np.int64(266), 'this movie in': np.int64(420), 'not to mention': np.int64(212), 'at the time': np.int64(46), 'the first place': np.int64(339), 'that there is': np.int64(300), 'this is very': np.int64(412), 'watch this movie': np.int64(483), 'better than the': np.int64(57), 'as bad as': np.int64(31), 'not to be': np.int64(211), 'falls in love': np.int64(83), 'you will be': np.int64(499), 'the movie that': np.int64(355), 'away from the': np.int64(47), 'the history of': np.int64(341), 'to watch it': np.int64(463), 'it in the': np.int64(166), 'along the way': np.int64(9), 'the middle of': np.int64(349), 'middle of the': np.int64(197), 'on the screen': np.int64(249), 'meant to be': np.int64(196), 'this film the': np.int64(403), 'like it was': np.int64(189), 'it was made': np.int64(178), 'to see what': np.int64(455), 'to go to': np.int64(442), 'in the same': np.int64(136), 'point of view': np.int64(265), 'watched this movie': np.int64(484), 'the acting was': np.int64(307), 'film it is': np.int64(87), 'to the film': np.int64(458), 'the entire movie': np.int64(324), 'and the film': np.int64(22), 'in order to': np.int64(122), 'of my favorite': np.int64(218), 'was in the': np.int64(477), 'it would have': np.int64(184), 'the role of': np.int64(371), 'the film to': np.int64(333), 'the movie has': np.int64(353), 'but this one': np.int64(68), 'one of his': np.int64(250), 'but if you': np.int64(61), 'when it was': np.int64(489), 'the story and': np.int64(376), 'it is the': np.int64(171), 'for the first': np.int64(90), 'the first time': np.int64(340), 'the part of': np.int64(364), 'as it was': np.int64(36), 'this film it': np.int64(402), 'it to the': np.int64(176), 'it was just': np.int64(177), 'this movie for': np.int64(418), 'and that is': np.int64(20), 'about this movie': np.int64(3), 'by the time': np.int64(71), 'the quality of': np.int64(369), 'is very good': np.int64(162), 'seemed to be': np.int64(279), 'with this movie': np.int64(492), 'up to the': np.int64(469), 'it is so': np.int64(170), 'recommend this film': np.int64(267), 'for the most': np.int64(91), 'the most part': np.int64(350), 'the film and': np.int64(326), 'should have been': np.int64(282), 'ive seen in': np.int64(188), 'but this movie': np.int64(67), 'there are few': np.int64(389), 'such as the': np.int64(289), 'and one of': np.int64(17), 'is probably the': np.int64(151), 'might have been': np.int64(198), 'along with the': np.int64(10), 'the characters were': np.int64(318), 'and some of': np.int64(19), 'from the first': np.int64(95), 'and all the': np.int64(11), 'this show is': np.int64(429), 'the world of': np.int64(386), 'reminded me of': np.int64(269), 'its one of': np.int64(186), 'to get the': np.int64(441), 'was able to': np.int64(475), 'that there are': np.int64(299), 'get to see': np.int64(97), 'is full of': np.int64(146), 'this is great': np.int64(407), 'in the story': np.int64(137), 'its hard to': np.int64(185), 'the big screen': np.int64(312), 'this kind of': np.int64(413), 'in fact the': np.int64(116), 'the bad guys': np.int64(309), 'in the original': np.int64(134), 'you get the': np.int64(496), 'in the early': np.int64(127), 'that they are': np.int64(301), 'with this film': np.int64(491), 'lot of the': np.int64(192), 'the kind of': np.int64(343), 'is the first': np.int64(157), 'saw this film': np.int64(271), 'dont waste your': np.int64(78), 'waste your time': np.int64(481), 'it is very': np.int64(172), 'in this case': np.int64(140), 'it if you': np.int64(165), 'with all the': np.int64(490), 'the supporting cast': np.int64(380), 'if you havent': np.int64(112), 'the film that': np.int64(331), 'this film but': np.int64(399), 'that he is': np.int64(291), 'of the main': np.int64(230), 'to the movie': np.int64(459), 'because it was': np.int64(54), 'movie it is': np.int64(204), 'you can see': np.int64(495), 'it was so': np.int64(180), 'there is nothing': np.int64(394), 'it is also': np.int64(167), 'it should be': np.int64(174), 'and the movie': np.int64(23), 'because it is': np.int64(53), 'go to the': np.int64(98), 'seem to have': np.int64(278), 'is going to': np.int64(147), 'watch this film': np.int64(482), 'much better than': np.int64(205), 'appears to be': np.int64(30), 'when it comes': np.int64(488), 'it comes to': np.int64(163), 'to make this': np.int64(447), 'it is an': np.int64(168), 'throughout the movie': np.int64(433), 'version of the': np.int64(471), 'there are many': np.int64(390), 'thing about this': np.int64(396), 'the script is': np.int64(374), 'that this was': np.int64(305), 'of the series': np.int64(238)}

In [47]:
cv=CountVectorizer(max_features=500, ngram_range=(1,3))
BoW=cv.fit_transform(df['review'])
print(cv.vocabulary_)

{'one': np.int64(282), 'of': np.int64(267), 'the': np.int64(377), 'other': np.int64(288), 'has': np.int64(150), 'that': np.int64(369), 'after': np.int64(8), 'watching': np.int64(461), 'just': np.int64(204), 'be': np.int64(44), 'they': np.int64(406), 'are': np.int64(30), 'right': np.int64(320), 'as': np.int64(32), 'this': np.int64(411), 'is': np.int64(185), 'what': np.int64(466), 'with': np.int64(479), 'first': np.int64(123), 'thing': np.int64(408), 'me': np.int64(238), 'about': np.int64(1), 'was': np.int64(456), 'its': np.int64(200), 'and': np.int64(21), 'scenes': np.int64(327), 'which': np.int64(470), 'set': np.int64(340), 'in': np.int64(176), 'from': np.int64(128), 'go': np.int64(139), 'not': np.int64(264), 'show': np.int64(346), 'for': np.int64(124), 'or': np.int64(286), 'no': np.int64(263), 'to': np.int64(426), 'classic': np.int64(73), 'use': np.int64(449), 'given': np.int64(138), 'it': np.int64(196), 'on': np.int64(279), 'an': np.int64(20), 'where': np.int64(469), 'all': np.int64(10), 'have': np.int64(151), 'so': np.int64(350), 'high': np.int64(162), 'home': np.int64(167), 'death': np.int64(84), 'never': np.int64(258), 'far': np.int64(115), 'would': np.int64(488), 'say': np.int64(325), 'main': np.int64(230), 'fact': np.int64(112), 'goes': np.int64(140), 'shows': np.int64(347), 'pretty': np.int64(307), 'doesnt': np.int64(91), 'around': np.int64(31), 'ever': np.int64(107), 'saw': np.int64(324), 'but': np.int64(60), 'watched': np.int64(460), 'more': np.int64(244), 'got': np.int64(144), 'out': np.int64(291), 'get': np.int64(133), 'away': np.int64(40), 'well': np.int64(464), 'being': np.int64(49), 'into': np.int64(183), 'their': np.int64(398), 'you': np.int64(495), 'may': np.int64(236), 'if': np.int64(173), 'can': np.int64(68), 'your': np.int64(498), 'one of': np.int64(283), 'of the': np.int64(272), 'the other': np.int64(390), 'they are': np.int64(407), 'this is': np.int64(414), 'from the': np.int64(129), 'is not': np.int64(188), 'for the': np.int64(125), 'in the': np.int64(179), 'that is': np.int64(371), 'is the': np.int64(193), 'to the': np.int64(434), 'all the': np.int64(12), 'on the': np.int64(280), 'the fact': np.int64(382), 'that it': np.int64(372), 'the first': np.int64(385), 'it was': np.int64(199), 'if you': np.int64(174), 'you can': np.int64(496), 'one of the': np.int64(284), 'little': np.int64(221), 'production': np.int64(309), 'very': np.int64(452), 'sense': np.int64(338), 'actors': np.int64(6), 'only': np.int64(285), 'he': np.int64(155), 'down': np.int64(94), 'too': np.int64(437), 'truly': np.int64(439), 'see': np.int64(332), 'by': np.int64(64), 'worth': np.int64(487), 'great': np.int64(145), 'comedy': np.int64(75), 'his': np.int64(165), 'life': np.int64(216), 'really': np.int64(315), 'comes': np.int64(76), 'things': np.int64(409), 'rather': np.int64(312), 'than': np.int64(368), 'then': np.int64(400), 'plays': np.int64(303), 'our': np.int64(290), 'every': np.int64(108), 'done': np.int64(92), 'is very': np.int64(194), 'by the': np.int64(65), 'but it': np.int64(61), 'it is': np.int64(198), 'and his': np.int64(22), 'with the': np.int64(480), 'and the': np.int64(24), 'thought': np.int64(421), 'way': np.int64(462), 'time': np.int64(424), 'plot': np.int64(304), 'characters': np.int64(72), 'even': np.int64(106), 'while': np.int64(472), 'some': np.int64(351), 'when': np.int64(467), 'point': np.int64(305), 'still': np.int64(359), 'many': np.int64(235), 'us': np.int64(448), 'most': np.int64(246), 'at': np.int64(35), 'years': np.int64(493), 'ive': np.int64(201), 'been': np.int64(47), 'she': np.int64(341), 'her': np.int64(159), 'young': np.int64(497), 'interesting': np.int64(182), 'friends': np.int64(127), 'this was': np.int64(418), 'the plot': np.int64(391), 'but the': np.int64(62), 'the characters': np.int64(380), 'was the': np.int64(457), 'the most': np.int64(386), 'in this': np.int64(180), 'of his': np.int64(270), 'theres': np.int64(404), 'family': np.int64(113), 'movie': np.int64(248), 'youre': np.int64(499), 'going': np.int64(141), 'make': np.int64(231), 'film': np.int64(119), 'must': np.int64(255), 'like': np.int64(217), 'real': np.int64(314), 'we': np.int64(463), 'instead': np.int64(181), '10': np.int64(0), 'them': np.int64(399), 'in his': np.int64(177), 'movie is': np.int64(250), 'of all': np.int64(268), 'going to': np.int64(142), 'to make': np.int64(431), 'the movie': np.int64(387), 'and then': np.int64(25), 'the film': np.int64(383), 'to see': np.int64(433), 'movie and': np.int64(249), 'out of': np.int64(292), 'love': np.int64(228), 'money': np.int64(243), 'watch': np.int64(459), 'seems': np.int64(335), 'do': np.int64(89), 'people': np.int64(297), 'different': np.int64(87), 'play': np.int64(301), 'same': np.int64(323), 'director': np.int64(88), 'action': np.int64(4), 'new': np.int64(259), 'these': np.int64(405), 'each': np.int64(97), 'another': np.int64(26), 'next': np.int64(260), 'know': np.int64(209), 'look': np.int64(223), 'how': np.int64(170), 'world': np.int64(485), 'own': np.int64(294), 'gets': np.int64(134), 'big': np.int64(54), 'best': np.int64(51), 'place': np.int64(300), 'find': np.int64(122), 'acting': np.int64(3), 'good': np.int64(143), 'rest': np.int64(319), 'cast': np.int64(70), 'come': np.int64(74), 'work': np.int64(484), 'the time': np.int64(394), 'to watch': np.int64(435), 'seems to': np.int64(336), 'to be': np.int64(427), 'about the': np.int64(2), 'the same': np.int64(392), 'the best': np.int64(379), 'most of': np.int64(247), 'probably': np.int64(308), 'my': np.int64(256), 'story': np.int64(360), 'boring': np.int64(58), 'old': np.int64(278), 'having': np.int64(154), 'seen': np.int64(337), 'times': np.int64(425), 'last': np.int64(210), 'performance': np.int64(298), 'few': np.int64(118), 'kids': np.int64(206), 'makes': np.int64(232), 'fun': np.int64(131), 'had': np.int64(147), 'up': np.int64(447), 'this movie': np.int64(415), 'sure': np.int64(363), 'series': np.int64(339), 'back': np.int64(42), 'black': np.int64(56), 'tv': np.int64(443), 'were': np.int64(465), 'need': np.int64(257), 'any': np.int64(27), 'believe': np.int64(50), 'nice': np.int64(261), 'read': np.int64(313), 'let': np.int64(215), 'the way': np.int64(395), 'like this': np.int64(219), 'would be': np.int64(489), 'is so': np.int64(191), 'idea': np.int64(172), 'off': np.int64(277), 'funny': np.int64(132), 'bad': np.int64(43), 'performances': np.int64(299), 'almost': np.int64(13), 'hard': np.int64(149), 'original': np.int64(287), 'also': np.int64(15), 'such': np.int64(362), 'give': np.int64(137), 'made': np.int64(229), 'now': np.int64(266), 'awful': np.int64(41), 'cant': np.int64(69), 'that the': np.int64(373), 'the original': np.int64(389), 'is just': np.int64(187), 'here': np.int64(160), 'looking': np.int64(224), 'films': np.int64(121), 'worst': np.int64(486), 'played': np.int64(302), 'less': np.int64(214), 'looks': np.int64(225), 'end': np.int64(101), 'least': np.int64(212), 'making': np.int64(233), 'bit': np.int64(55), 'this film': np.int64(412), 'the worst': np.int64(397), 'of them': np.int64(275), 'have been': np.int64(152), 'the end': np.int64(381), 'the only': np.int64(388), 'at least': np.int64(37), 'will': np.int64(478), 'those': np.int64(419), 'everything': np.int64(110), 'didnt': np.int64(86), 'thats': np.int64(376), 'there': np.int64(401), 'who': np.int64(473), 'something': np.int64(355), 'better': np.int64(52), 'try': np.int64(440), 'is one': np.int64(189), 'as the': np.int64(33), 'who is': np.int64(474), 'is one of': np.int64(190), 'came': np.int64(66), 'scene': np.int64(326), 'men': np.int64(239), 'horror': np.int64(168), 'movies': np.int64(252), 'beautiful': np.int64(45), 'woman': np.int64(482), 'might': np.int64(240), 'much': np.int64(253), 'year': np.int64(492), 'later': np.int64(211), 'star': np.int64(357), 'since': np.int64(349), 'when the': np.int64(468), 'the story': np.int64(393), 'there are': np.int64(402), 'im': np.int64(175), 'fan': np.int64(114), 'again': np.int64(9), 'maybe': np.int64(237), 'long': np.int64(222), 'before': np.int64(48), 'should': np.int64(345), 'together': np.int64(436), 'along': np.int64(14), 'three': np.int64(422), 'actually': np.int64(7), 'however': np.int64(171), 'hes': np.int64(161), 'true': np.int64(438), 'whole': np.int64(475), 'dont': np.int64(93), 'reason': np.int64(316), 'did': np.int64(85), 'until': np.int64(446), 'take': np.int64(364), 'him': np.int64(163), 'minutes': np.int64(242), 'screen': np.int64(329), 'that this': np.int64(374), 'the whole': np.int64(396), 'he was': np.int64(157), 'film is': np.int64(120), 'of it': np.int64(271), 'this movie is': np.int64(416), 'this film is': np.int64(413), 'of the film': np.int64(273), 'trying': np.int64(441), 'why': np.int64(476), 'because': np.int64(46), 'keep': np.int64(205), 'does': np.int64(90), 'trying to': np.int64(442), 'is that': np.int64(192), 'to do': np.int64(428), 'have to': np.int64(153), 'man': np.int64(234), 'but this': np.int64(63), 'kind': np.int64(207), 'school': np.int64(328), 'quite': np.int64(311), 'could': np.int64(78), 'kind of': np.int64(208), 'to get': np.int64(429), 'this one': np.int64(417), 'could have': np.int64(79), 'simply': np.int64(348), 'excellent': np.int64(111), 'always': np.int64(17), 'feel': np.int64(117), 'character': np.int64(71), 'version': np.int64(451), 'special': np.int64(356), 'effects': np.int64(98), 'enjoy': np.int64(103), 'some of': np.int64(352), 'some of the': np.int64(353), 'wasnt': np.int64(458), 'both': np.int64(59), 'someone': np.int64(354), 'tell': np.int64(366), 'line': np.int64(220), 'either': np.int64(99), 'at the': np.int64(38), 'to say': np.int64(432), 'remember': np.int64(318), 'actor': np.int64(5), 'think': np.int64(410), 'shot': np.int64(344), 'anyone': np.int64(28), 'dvd': np.int64(96), 'others': np.int64(289), 'which is': np.int64(471), 'script': np.int64(330), 'enough': np.int64(104), 'couple': np.int64(80), 'of this': np.int64(276), 'would have': np.int64(490), 'wrong': np.int64(491), 'guy': np.int64(146), 'especially': np.int64(105), 'full': np.int64(130), 'john': np.int64(203), 'girl': np.int64(136), 'help': np.int64(158), 'terrible': np.int64(367), 'women': np.int64(483), 'at all': np.int64(36), 'all of': np.int64(11), 'it has': np.int64(197), 'although': np.int64(16), 'isnt': np.int64(195), 'anything': np.int64(29), 'music': np.int64(254), 'takes': np.int64(365), 'start': np.int64(358), 'am': np.int64(18), 'used': np.int64(450), 'over': np.int64(293), 'night': np.int64(262), 'stupid': np.int64(361), 'like the': np.int64(218), 'part': np.int64(295), 'and it': np.int64(23), 'the acting': np.int64(378), 'there is': np.int64(403), 'though': np.int64(420), 'role': np.int64(321), 'job': np.int64(202), 'she is': np.int64(342), 'movie was': np.int64(251), 'mind': np.int64(241), 'want': np.int64(453), 'nothing': np.int64(265), 'else': np.int64(100), 'audience': np.int64(39), 'lot': np.int64(226), 'is an': np.int64(186), 'more than': np.int64(245), 'into the': np.int64(184), 'to have': np.int64(430), 'lot of': np.int64(227), 'once': np.int64(281), 'hollywood': np.int64(166), 'war': np.int64(455), 'poor': np.int64(306), 'seem': np.int64(334), 'left': np.int64(213), 'course': np.int64(81), 'put': np.int64(310), 'two': np.int64(444), 'father': np.int64(116), 'between': np.int64(53), 'second': np.int64(331), 'that he': np.int64(370), 'himself': np.int64(164), 'house': np.int64(169), 'short': np.int64(343), 'through': np.int64(423), 'he is': np.int64(156), 'part of': np.int64(296), 'the film is': np.int64(384), 'yet': np.int64(494), 'without': np.int64(481), 'half': np.int64(148), 'during': np.int64(95), 'of the movie': np.int64(274), 'completely': np.int64(77), 'of course': np.int64(269), 'camera': np.int64(67), 'recommend': np.int64(317), 'book': np.int64(57), 'ending': np.int64(102), 'american': np.int64(19), 'as well': np.int64(34), 'in my': np.int64(178), 'wife': np.int64(477), 'getting': np.int64(135), 'found': np.int64(126), 'day': np.int64(82), 'seeing': np.int64(333), 'dead': np.int64(83), 'want to': np.int64(454), 'that was': np.int64(375), 'everyone': np.int64(109), 'said': np.int64(322), 'understand': np.int64(445)}

In [48]:
cv=CountVectorizer(max_features=500, ngram_range=(2,3))
BoW=cv.fit_transform(df['review'])
print(cv.vocabulary_)

{'one of': np.int64(269), 'of the': np.int64(250), 'the other': np.int64(367), 'they are': np.int64(397), 'this is': np.int64(403), 'from the': np.int64(104), 'is not': np.int64(168), 'for the': np.int64(102), 'this show': np.int64(410), 'in the': np.int64(147), 'that is': np.int64(317), 'is the': np.int64(175), 'to the': np.int64(435), 'all the': np.int64(7), 'on the': np.int64(266), 'the main': np.int64(355), 'the show': np.int64(380), 'due to': np.int64(78), 'the fact': np.int64(346), 'fact that': np.int64(88), 'that it': np.int64(318), 'the first': np.int64(352), 'it was': np.int64(194), 'for it': np.int64(99), 'it but': np.int64(181), 'lack of': np.int64(201), 'what is': np.int64(468), 'if you': np.int64(132), 'you can': np.int64(493), 'one of the': np.int64(270), 'the fact that': np.int64(347), 'is very': np.int64(177), 'sense of': np.int64(296), 'the entire': np.int64(345), 'the actors': np.int64(330), 'not only': np.int64(236), 'but he': np.int64(59), 'he has': np.int64(123), 'see the': np.int64(291), 'by the': np.int64(67), 'is it': np.int64(164), 'but it': np.int64(61), 'it is': np.int64(188), 'the great': np.int64(353), 'and his': np.int64(14), 'with the': np.int64(487), 'rather than': np.int64(285), 'and the': np.int64(24), 'of their': np.int64(255), 'this was': np.int64(411), 'way to': np.int64(464), 'the plot': np.int64(369), 'plot is': np.int64(284), 'but the': np.int64(64), 'the characters': np.int64(339), 'characters are': np.int64(69), 'even the': np.int64(85), 'may be': np.int64(214), 'when they': np.int64(475), 'is still': np.int64(173), 'many of': np.int64(213), 'was the': np.int64(457), 'the most': np.int64(357), 'in this': np.int64(152), 'not be': np.int64(234), 'be the': np.int64(51), 'of his': np.int64(245), 'to go': np.int64(422), 'in his': np.int64(140), 'movie is': np.int64(221), 'of all': np.int64(240), 'going to': np.int64(110), 'to make': np.int64(429), 'the movie': np.int64(358), 'and then': np.int64(25), 'we have': np.int64(466), 'with his': np.int64(485), 'the film': np.int64(348), 'to see': np.int64(432), 'movie and': np.int64(218), 'with some': np.int64(486), 'out of': np.int64(273), 'of 10': np.int64(239), 'the movie is': np.int64(359), 'out of 10': np.int64(274), 'the time': np.int64(383), 'film to': np.int64(95), 'to watch': np.int64(437), 'movie that': np.int64(223), 'seems to': np.int64(294), 'to be': np.int64(416), 'about the': np.int64(2), 'the same': np.int64(374), 'the director': np.int64(340), 'one is': np.int64(268), 'the next': np.int64(362), 'no one': np.int64(233), 'to know': np.int64(428), 'we are': np.int64(465), 'the world': np.int64(390), 'in their': np.int64(151), 'the best': np.int64(333), 'in which': np.int64(155), 'most of': np.int64(216), 'the people': np.int64(368), 'acting is': np.int64(4), 'is good': np.int64(161), 'the rest': np.int64(372), 'rest of': np.int64(286), 'for his': np.int64(98), 'seems to be': np.int64(295), 'most of the': np.int64(217), 'the rest of': np.int64(373), 'rest of the': np.int64(287), 'story of': np.int64(310), 'but its': np.int64(62), 'its not': np.int64(197), 'it just': np.int64(189), 'the last': np.int64(354), 'of her': np.int64(244), 'for this': np.int64(103), 'this movie': np.int64(406), 'like to': np.int64(205), 'they have': np.int64(398), 'it would': np.int64(195), 'and this': np.int64(28), 'the way': np.int64(388), 'like this': np.int64(204), 'would be': np.int64(489), 'out to': np.int64(277), 'and have': np.int64(11), 'is so': np.int64(172), 'when it': np.int64(473), 'was not': np.int64(455), 'and its': np.int64(18), 'waste of': np.int64(459), 'of time': np.int64(262), 'hard to': np.int64(114), 'that the': np.int64(321), 'the original': np.int64(366), 'as it': np.int64(38), 'is just': np.int64(165), 'about this': np.int64(3), 'this film': np.int64(401), 'watching this': np.int64(463), 'ive seen': np.int64(198), 'the worst': np.int64(391), 'of them': np.int64(256), 'the films': np.int64(350), 'and is': np.int64(16), 'have been': np.int64(118), 'the end': np.int64(342), 'of film': np.int64(243), 'film the': np.int64(94), 'the only': np.int64(365), 'at least': np.int64(44), 'bit of': np.int64(57), 'of an': np.int64(241), 'you will': np.int64(499), 'you are': np.int64(492), 'if you are': np.int64(133), 'is one': np.int64(169), 'of those': np.int64(261), 'where the': np.int64(477), 'was very': np.int64(458), 'as the': np.int64(39), 'there were': np.int64(396), 'who is': np.int64(481), 'is one of': np.int64(170), 'one of those': np.int64(271), 'saw this': np.int64(288), 'the big': np.int64(334), 'when the': np.int64(474), 'up and': np.int64(442), 'up the': np.int64(444), 'the story': np.int64(381), 'make it': np.int64(211), 'up to': np.int64(445), 'and not': np.int64(19), 'there are': np.int64(392), 'out of the': np.int64(275), 'in the end': np.int64(148), 'in the film': np.int64(149), 'im not': np.int64(135), 'fan of': np.int64(89), 'people who': np.int64(281), 'should be': np.int64(299), 'that this': np.int64(324), 'along with': np.int64(8), 'played by': np.int64(283), 'the whole': np.int64(389), 'know what': np.int64(200), 'when he': np.int64(472), 'he was': np.int64(125), 'film is': np.int64(92), 'as they': np.int64(40), 'for some': np.int64(101), 'see this': np.int64(292), 'of it': np.int64(246), 'that would': np.int64(326), 'such as': np.int64(311), 'the scene': np.int64(375), 'in the movie': np.int64(150), 'in this movie': np.int64(154), 'this movie is': np.int64(407), 'in this film': np.int64(153), 'this film is': np.int64(402), 'of the film': np.int64(252), 'the cast': np.int64(337), 'trying to': np.int64(441), 'because the': np.int64(54), 'my favorite': np.int64(231), 'do not': np.int64(75), 'is that': np.int64(174), 'to do': np.int64(418), 'have to': np.int64(122), 'to keep': np.int64(427), 'say that': np.int64(289), 'does not': np.int64(76), 'but this': np.int64(66), 'the man': np.int64(356), 'movie to': np.int64(225), 'kind of': np.int64(199), 'ever seen': np.int64(87), 'sort of': np.int64(306), 'what was': np.int64(471), 'in that': np.int64(146), 'to get': np.int64(420), 'with this': np.int64(488), 'this one': np.int64(409), 'lots of': np.int64(210), 'could have': np.int64(71), 'of the most': np.int64(253), 'could have been': np.int64(72), 'film but': np.int64(91), 'as he': np.int64(36), 'up with': np.int64(446), 'did not': np.int64(74), 'the character': np.int64(338), 'in its': np.int64(142), 'some of': np.int64(304), 'special effects': np.int64(307), 'much more': np.int64(229), 'this is one': np.int64(404), 'some of the': np.int64(305), 'of my': np.int64(248), 'there was': np.int64(395), 'they were': np.int64(399), 'wanted to': np.int64(451), 'at the': np.int64(45), 'the final': np.int64(351), 'the old': np.int64(363), 'the beginning': np.int64(332), 'time and': np.int64(415), 'if it': np.int64(129), 'much of': np.int64(230), 'to say': np.int64(431), 'at the end': np.int64(46), 'to find': np.int64(419), 'has been': np.int64(115), 'which is': np.int64(478), 'have seen': np.int64(120), 'like it': np.int64(202), 'if the': np.int64(130), 'of this': np.int64(258), 'would have': np.int64(490), 'couple of': np.int64(73), 'after the': np.int64(5), 'those who': np.int64(412), 'who are': np.int64(479), 'in all': np.int64(136), 'full of': np.int64(105), 'to her': np.int64(424), 'go to': np.int64(109), 'if youre': np.int64(134), 'looking for': np.int64(207), 'the one': np.int64(364), 'had the': np.int64(112), 'because it': np.int64(52), 'movie the': np.int64(224), 'story is': np.int64(309), 'at all': np.int64(43), 'all of': np.int64(6), 'it has': np.int64(186), 'are so': np.int64(33), 'supposed to': np.int64(312), 'in it': np.int64(141), 'try to': np.int64(440), 'and they': np.int64(27), 'to be the': np.int64(417), 'the story is': np.int64(382), 'supposed to be': np.int64(313), 'you have': np.int64(495), 'watch it': np.int64(460), 'too much': np.int64(438), 'on his': np.int64(265), 'it the': np.int64(192), 'the music': np.int64(361), 'like the': np.int64(203), 'it seems': np.int64(191), 'on this': np.int64(267), 'in fact': np.int64(138), 'bunch of': np.int64(58), 'to take': np.int64(434), 'the dvd': np.int64(341), 'to show': np.int64(433), 'to give': np.int64(421), 'this is the': np.int64(405), 'and it': np.int64(17), 'based on': np.int64(50), 'much better': np.int64(228), 'than the': np.int64(314), 'the acting': np.int64(328), 'there is': np.int64(393), 'is no': np.int64(167), 'to me': np.int64(430), 'not even': np.int64(235), 'the acting is': np.int64(329), 'there is no': np.int64(394), 'she is': np.int64(297), 'think that': np.int64(400), 'movie was': np.int64(226), 'this movie was': np.int64(408), 'is an': np.int64(160), 'of what': np.int64(263), 'can be': np.int64(68), 'is to': np.int64(176), 'the point': np.int64(370), 'it and': np.int64(179), 'more than': np.int64(215), 'into the': np.int64(157), 'looks like': np.int64(208), 'wants to': np.int64(452), 'what it': np.int64(469), 'film was': np.int64(96), 'movie with': np.int64(227), 'to have': np.int64(423), 'was just': np.int64(454), 'lot of': np.int64(209), 'will be': np.int64(482), 'it in': np.int64(187), 'was so': np.int64(456), 'and was': np.int64(29), 'able to': np.int64(0), 'so much': np.int64(303), 'need to': np.int64(232), 'had to': np.int64(113), 'of its': np.int64(247), 'so many': np.int64(302), 'is about': np.int64(158), 'the audience': np.int64(331), 'and even': np.int64(10), 'at times': np.int64(47), 'as an': np.int64(35), 'end of': np.int64(81), 'end of the': np.int64(82), 'the second': np.int64(378), 'who has': np.int64(480), 'that he': np.int64(316), 'even though': np.int64(86), 'his own': np.int64(127), 'him to': np.int64(126), 'he is': np.int64(124), 'part of': np.int64(279), 'the film is': np.int64(349), 'of the best': np.int64(251), 'the movie was': np.int64(360), 'in an': np.int64(137), 'when you': np.int64(476), 'it does': np.int64(182), 'is also': np.int64(159), 'between the': np.int64(56), 'and in': np.int64(15), 'out the': np.int64(276), 'film that': np.int64(93), 'of that': np.int64(249), 'during the': np.int64(79), 'and you': np.int64(30), 'you know': np.int64(496), 'movie has': np.int64(220), 'about it': np.int64(1), 'that its': np.int64(319), 'its just': np.int64(196), 'movie but': np.int64(219), 'watch this': np.int64(462), 'because of': np.int64(53), 'of the movie': np.int64(254), 'is in': np.int64(163), 'in her': np.int64(139), 'version of': np.int64(447), 'but they': np.int64(65), 'but not': np.int64(63), 'to this': np.int64(436), 'has to': np.int64(117), 'movie it': np.int64(222), 'watch the': np.int64(461), 'that are': np.int64(315), 'or the': np.int64(272), 'throughout the': np.int64(414), 'of course': np.int64(242), 'see it': np.int64(290), 'the camera': np.int64(336), 'it had': np.int64(185), 'the script': np.int64(377), 'the end of': np.int64(343), 'the book': np.int64(335), 'up in': np.int64(443), 'the two': np.int64(385), 'the ending': np.int64(344), 'off the': np.int64(264), 'are not': np.int64(32), 'not to': np.int64(238), 'with an': np.int64(483), 'get to': np.int64(107), 'each other': np.int64(80), 'for me': np.int64(100), 'have the': np.int64(121), 'and that': np.int64(23), 'but in': np.int64(60), 'as well': np.int64(41), 'well as': np.int64(467), 'in my': np.int64(144), 'as well as': np.int64(42), 'through the': np.int64(413), 'could be': np.int64(70), 'and all': np.int64(9), 'would have been': np.int64(491), 'not the': np.int64(237), 'his wife': np.int64(128), 'and he': np.int64(12), 'enough to': np.int64(83), 'away from': np.int64(48), 'make the': np.int64(212), 'and some': np.int64(22), 'instead of': np.int64(156), 'over the': np.int64(278), 'in love': np.int64(143), 'with her': np.int64(484), 'to his': np.int64(425), 'back to': np.int64(49), 'it all': np.int64(178), 'of these': np.int64(257), 'better than': np.int64(55), 'story and': np.int64(308), 'the screen': np.int64(376), 'the viewer': np.int64(387), 'it to': np.int64(193), 'want to': np.int64(450), 'it doesnt': np.int64(183), 'for her': np.int64(97), 'that was': np.int64(325), 'is really': np.int64(171), 'that there': np.int64(322), 'you want': np.int64(497), 'of this movie': np.int64(260), 'you want to': np.int64(498), 'that she': np.int64(320), 'in some': np.int64(145), 'is more': np.int64(166), 'piece of': np.int64(282), 'the title': np.int64(384), 'that they': np.int64(323), 'of this film': np.int64(259), 'give it': np.int64(108), 'it for': np.int64(184), 'tries to': np.int64(439), 'even if': np.int64(84), 'has the': np.int64(116), 'the real': np.int64(371), 'she was': np.int64(298), 'the very': np.int64(386), 'are the': np.int64(34), 'seem to': np.int64(293), 'that you': np.int64(327), 'so bad': np.int64(301), 'get the': np.int64(106), 'and there': np.int64(26), 'what the': np.int64(470), 'have ever': np.int64(119), 'dont know': np.int64(77), 'you dont': np.int64(494), 'to it': np.int64(426), 'any of': np.int64(31), 'film and': np.int64(90), 'if they': np.int64(131), 'and her': np.int64(13), 'look at': np.int64(206), 'very good': np.int64(448), 'part of the': np.int64(280), 'as if': np.int64(37), 'should have': np.int64(300), 'and so': np.int64(21), 'is great': np.int64(162), 'had been': np.int64(111), 'it as': np.int64(180), 'very well': np.int64(449), 'was in': np.int64(453), 'and she': np.int64(20), 'the series': np.int64(379), 'it on': np.int64(190)}

In [49]:
# Problem 6

# Apply tf-idf and find out the idf scores of words, also find out the vocabulary.

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer 

tfidf=TfidfVectorizer(max_features=500)

x= tfidf.fit_transform(df['review']) 

print(tfidf.vocabulary_)

{'one': np.int64(299), 'of': np.int64(292), 'the': np.int64(402), 'other': np.int64(303), 'has': np.int64(180), 'that': np.int64(400), 'after': np.int64(10), 'watching': np.int64(458), 'just': np.int64(220), 'episode': np.int64(120), 'youll': np.int64(496), 'be': np.int64(39), 'they': np.int64(409), 'are': np.int64(29), 'right': np.int64(343), 'as': np.int64(31), 'this': np.int64(414), 'is': np.int64(212), 'what': np.int64(464), 'with': np.int64(475), 'first': np.int64(148), 'thing': np.int64(411), 'me': np.int64(262), 'about': np.int64(2), 'was': np.int64(453), 'its': np.int64(215), 'and': np.int64(24), 'scenes': np.int64(350), 'which': np.int64(467), 'set': np.int64(363), 'in': np.int64(208), 'from': np.int64(154), 'go': np.int64(168), 'not': np.int64(289), 'show': np.int64(371), 'for': np.int64(150), 'or': np.int64(301), 'no': np.int64(288), 'to': np.int64(424), 'sex': np.int64(365), 'classic': np.int64(76), 'use': np.int64(444), 'called': np.int64(63), 'given': np.int64(166), 'it': np.int64(214), 'on': np.int64(297), 'an': np.int64(23), 'where': np.int64(466), 'all': np.int64(13), 'have': np.int64(181), 'face': np.int64(131), 'so': np.int64(377), 'high': np.int64(189), 'home': np.int64(195), 'death': np.int64(89), 'never': np.int64(283), 'far': np.int64(136), 'would': np.int64(487), 'say': np.int64(348), 'main': np.int64(253), 'fact': np.int64(132), 'goes': np.int64(169), 'shows': np.int64(372), 'pretty': np.int64(328), 'doesnt': np.int64(100), 'around': np.int64(30), 'ever': np.int64(123), 'saw': np.int64(347), 'couldnt': np.int64(82), 'but': np.int64(61), 'watched': np.int64(457), 'more': np.int64(271), 'got': np.int64(172), 'out': np.int64(306), 'kill': np.int64(223), 'get': np.int64(160), 'away': np.int64(34), 'well': np.int64(461), 'being': np.int64(48), 'into': np.int64(211), 'their': np.int64(403), 'you': np.int64(495), 'may': np.int64(260), 'become': np.int64(42), 'if': np.int64(206), 'can': np.int64(66), 'your': np.int64(498), 'side': np.int64(373), 'wonderful': np.int64(479), 'little': np.int64(240), 'production': np.int64(331), 'very': np.int64(447), 'gives': np.int64(167), 'sense': np.int64(361), 'entire': np.int64(119), 'piece': np.int64(319), 'actors': np.int64(8), 'michael': np.int64(265), 'only': np.int64(300), 'he': np.int64(183), 'down': np.int64(104), 'too': np.int64(426), 'truly': np.int64(431), 'see': np.int64(355), 'by': np.int64(62), 'worth': np.int64(486), 'written': np.int64(489), 'great': np.int64(173), 'comedy': np.int64(78), 'his': np.int64(192), 'life': np.int64(235), 'really': np.int64(338), 'comes': np.int64(79), 'things': np.int64(412), 'rather': np.int64(335), 'than': np.int64(399), 'then': np.int64(405), 'plays': np.int64(324), 'our': np.int64(305), 'every': np.int64(124), 'done': np.int64(102), 'thought': np.int64(417), 'way': np.int64(459), 'time': np.int64(421), 'plot': np.int64(325), 'dialogue': np.int64(92), 'characters': np.int64(73), 'even': np.int64(122), 'killer': np.int64(224), 'while': np.int64(468), 'some': np.int64(378), 'when': np.int64(465), 'point': np.int64(326), 'still': np.int64(388), 'style': np.int64(391), 'many': np.int64(258), 'us': np.int64(443), 'most': np.int64(272), 'id': np.int64(204), 'at': np.int64(32), 'years': np.int64(492), 'ive': np.int64(217), 'been': np.int64(44), 'she': np.int64(366), 'her': np.int64(186), 'young': np.int64(497), 'interesting': np.int64(210), 'friends': np.int64(153), 'theres': np.int64(407), 'family': np.int64(133), 'boy': np.int64(59), 'movie': np.int64(274), 'youre': np.int64(499), 'going': np.int64(170), 'make': np.int64(254), 'film': np.int64(142), 'must': np.int64(279), 'drama': np.int64(105), 'like': np.int64(236), 'real': np.int64(337), 'we': np.int64(460), 'totally': np.int64(428), 'instead': np.int64(209), '10': np.int64(0), 'playing': np.int64(323), 'them': np.int64(404), 'love': np.int64(249), 'money': np.int64(270), 'watch': np.int64(456), 'mr': np.int64(276), 'human': np.int64(202), 'seems': np.int64(359), 'do': np.int64(98), 'people': np.int64(312), 'different': np.int64(95), 'play': np.int64(321), 'same': np.int64(346), 'director': np.int64(97), 'action': np.int64(6), 'new': np.int64(284), 'these': np.int64(408), 'each': np.int64(108), 'another': np.int64(25), 'next': np.int64(285), 'person': np.int64(317), 'know': np.int64(226), 'look': np.int64(244), 'how': np.int64(200), 'live': np.int64(241), 'world': np.int64(483), 'own': np.int64(308), 'gets': np.int64(161), 'picture': np.int64(318), 'big': np.int64(53), 'best': np.int64(50), 'place': np.int64(320), 'find': np.int64(146), 'case': np.int64(69), 'acting': np.int64(5), 'good': np.int64(171), 'under': np.int64(438), 'direction': np.int64(96), 'rest': np.int64(342), 'cast': np.int64(70), 'come': np.int64(77), 'work': np.int64(481), 'probably': np.int64(329), 'my': np.int64(280), 'favorite': np.int64(138), 'story': np.int64(389), 'boring': np.int64(57), 'old': np.int64(296), 'despite': np.int64(91), 'having': np.int64(182), 'seen': np.int64(360), 'times': np.int64(422), 'last': np.int64(227), 'performance': np.int64(314), 'few': np.int64(141), 'kids': np.int64(222), 'children': np.int64(74), 'makes': np.int64(255), 'fun': np.int64(156), 'had': np.int64(177), 'up': np.int64(442), 'sure': np.int64(394), 'series': np.int64(362), 'back': np.int64(36), 'black': np.int64(55), 'white': np.int64(469), 'tv': np.int64(436), 'were': np.int64(463), 'need': np.int64(282), 'any': np.int64(26), 'believe': np.int64(49), 'nice': np.int64(286), 'read': np.int64(336), 'lines': np.int64(239), 'let': np.int64(234), 'amazing': np.int64(21), 'idea': np.int64(205), 'off': np.int64(293), 'funny': np.int64(157), 'waste': np.int64(455), 'writing': np.int64(488), 'bad': np.int64(37), 'performances': np.int64(315), 'almost': np.int64(14), 'entertaining': np.int64(118), 'hard': np.int64(179), 'original': np.int64(302), 'also': np.int64(17), 'such': np.int64(392), 'felt': np.int64(140), 'give': np.int64(165), 'stars': np.int64(386), 'made': np.int64(252), 'now': np.int64(291), 'awful': np.int64(35), 'cant': np.int64(67), 'here': np.int64(187), 'looking': np.int64(245), 'films': np.int64(143), 'worst': np.int64(485), 'played': np.int64(322), 'less': np.int64(233), 'looks': np.int64(246), 'end': np.int64(113), 'least': np.int64(231), 'making': np.int64(256), 'bit': np.int64(54), 'will': np.int64(474), 'liked': np.int64(237), 'those': np.int64(415), 'based': np.int64(38), 'everything': np.int64(126), 'didnt': np.int64(94), 'low': np.int64(251), 'budget': np.int64(60), 'thats': np.int64(401), 'problem': np.int64(330), 'itself': np.int64(216), 'there': np.int64(406), 'lost': np.int64(247), 'who': np.int64(470), 'something': np.int64(380), 'better': np.int64(51), 'try': np.int64(432), 'came': np.int64(64), 'scene': np.int64(349), 'men': np.int64(264), 'horror': np.int64(198), 'movies': np.int64(275), 'beautiful': np.int64(40), 'woman': np.int64(477), 'might': np.int64(266), 'care': np.int64(68), 'much': np.int64(277), 'year': np.int64(491), 'later': np.int64(228), 'loved': np.int64(250), 'star': np.int64(385), 'early': np.int64(109), 'since': np.int64(375), 'im': np.int64(207), 'fan': np.int64(134), 'again': np.int64(11), 'enjoyed': np.int64(116), 'maybe': np.int64(261), 'long': np.int64(243), 'before': np.int64(45), 'game': np.int64(158), 'should': np.int64(370), 'together': np.int64(425), 'along': np.int64(15), 'three': np.int64(418), 'actually': np.int64(9), 'yes': np.int64(493), 'however': np.int64(201), 'hes': np.int64(188), 'true': np.int64(430), 'whole': np.int64(471), 'dont': np.int64(103), 'evil': np.int64(127), 'reason': np.int64(339), 'did': np.int64(93), 'until': np.int64(441), 'laugh': np.int64(229), 'take': np.int64(395), 'him': np.int64(190), 'minutes': np.int64(268), 'screen': np.int64(352), 'trying': np.int64(433), 'why': np.int64(472), 'because': np.int64(41), 'keep': np.int64(221), 'does': np.int64(99), 'man': np.int64(257), 'kind': np.int64(225), 'sort': np.int64(382), 'school': np.int64(351), 'supposed': np.int64(393), 'quite': np.int64(334), 'could': np.int64(81), 'simply': np.int64(374), 'title': np.int64(423), 'excellent': np.int64(129), 'always': np.int64(19), 'feel': np.int64(139), 'character': np.int64(72), 'version': np.int64(446), 'special': np.int64(384), 'effects': np.int64(110), 'enjoy': np.int64(115), 'top': np.int64(427), 'horrible': np.int64(197), 'wasnt': np.int64(454), 'wanted': np.int64(450), 'final': np.int64(144), 'beginning': np.int64(46), 'both': np.int64(58), 'someone': np.int64(379), 'tell': np.int64(397), 'line': np.int64(238), 'either': np.int64(111), 'remember': np.int64(341), 'cinema': np.int64(75), 'dark': np.int64(85), 'actor': np.int64(7), 'think': np.int64(413), 'shot': np.int64(369), 'anyone': np.int64(27), 'dvd': np.int64(107), 'others': np.int64(304), 'against': np.int64(12), 'fine': np.int64(147), 'script': np.int64(353), 'enough': np.int64(117), 'couple': np.int64(83), 'wrong': np.int64(490), 'guy': np.int64(175), 'especially': np.int64(121), 'full': np.int64(155), 'john': np.int64(219), 'girl': np.int64(163), 'help': np.int64(185), 'turn': np.int64(434), 'terrible': np.int64(398), 'women': np.int64(478), 'absolutely': np.int64(3), 'wont': np.int64(480), 'although': np.int64(18), 'isnt': np.int64(213), 'anything': np.int64(28), 'music': np.int64(278), 'takes': np.int64(396), 'start': np.int64(387), 'am': np.int64(20), 'matter': np.int64(259), 'used': np.int64(445), 'several': np.int64(364), 'theyre': np.int64(410), 'worse': np.int64(484), 'over': np.int64(307), 'night': np.int64(287), 'stupid': np.int64(390), 'shes': np.int64(367), 'part': np.int64(309), 'though': np.int64(416), 'role': np.int64(344), 'job': np.int64(218), 'unfortunately': np.int64(440), 'mind': np.int64(267), 'want': np.int64(449), 'nothing': np.int64(290), 'wants': np.int64(451), 'guess': np.int64(174), 'else': np.int64(112), 'audience': np.int64(33), 'lot': np.int64(248), 'once': np.int64(298), 'hollywood': np.int64(194), 'behind': np.int64(47), 'war': np.int64(452), 'poor': np.int64(327), 'seemed': np.int64(358), 'able': np.int64(1), 'seem': np.int64(357), 'becomes': np.int64(43), 'left': np.int64(232), 'turns': np.int64(435), 'course': np.int64(84), 'put': np.int64(332), 'perhaps': np.int64(316), 'two': np.int64(437), 'father': np.int64(137), 'mother': np.int64(273), 'past': np.int64(311), 'between': np.int64(52), 'lives': np.int64(242), 'second': np.int64(354), 'small': np.int64(376), 'works': np.int64(482), 'himself': np.int64(191), 'finally': np.int64(145), 'house': np.int64(199), 'short': np.int64(368), 'through': np.int64(419), 'video': np.int64(448), 'quality': np.int64(333), 'yet': np.int64(494), 'without': np.int64(476), 'half': np.int64(178), 'days': np.int64(87), 'friend': np.int64(152), 'during': np.int64(106), 'expect': np.int64(130), 'gave': np.int64(159), 'lead': np.int64(230), 'certainly': np.int64(71), 'humor': np.int64(203), 'throughout': np.int64(420), 'act': np.int64(4), 'completely': np.int64(80), 'hope': np.int64(196), 'camera': np.int64(65), 'went': np.int64(462), 'recommend': np.int64(340), 'book': np.int64(56), 'moments': np.int64(269), 'ending': np.int64(114), 'example': np.int64(128), 'american': np.int64(22), 'parts': np.int64(310), 'head': np.int64(184), 'wife': np.int64(473), 'son': np.int64(381), 'getting': np.int64(162), 'sound': np.int64(383), 'already': np.int64(16), 'found': np.int64(151), 'day': np.int64(86), 'seeing': np.int64(356), 'dead': np.int64(88), 'fans': np.int64(135), 'often': np.int64(294), 'perfect': np.int64(313), 'definitely': np.int64(90), 'name': np.int64(281), 'everyone': np.int64(125), 'doing': np.int64(101), 'tries': np.int64(429), 'flick': np.int64(149), 'girls': np.int64(164), 'guys': np.int64(176), 'oh': np.int64(295), 'mean': np.int64(263), 'said': np.int64(345), 'understand': np.int64(439), 'history': np.int64(193)}

In [53]:
print(tfidf.idf_ ) 
print(tfidf.get_feature_names_out())

[3.64537713 4.06832297 1.88456985 3.89681233 4.17823384 2.57081429
 3.48292865 3.63249901 2.94773177 2.99718134 2.51224046 3.11496437
 4.02827547 1.68440567 3.25705828 3.72664159 4.04410253 2.38919852
 3.51753249 3.26608032 3.36917234 4.17201224 3.77292877 1.7257317
 1.036601   2.98546131 2.48220871 3.39823532 3.31265543 1.59538733
 3.15005569 1.45547399 1.67379602 3.70188934 3.3799182  3.92585315
 2.92020392 2.47580153 4.01840696 1.57862495 3.67424865 2.40513028
 3.9599991  4.08087453 2.34027082 2.97243841 3.99176025 4.17058196
 2.61135972 3.44578286 2.6639141  2.71293132 3.23606857 3.22213171
 3.31346384 3.86718317 3.953076   3.83909046 3.23214663 4.14704039
 3.9989574  1.35489656 1.76866689 4.06061085 3.80315041 3.93409289
 2.17120298 3.06327328 4.06360294 3.96270442 3.10917876 3.94696211
 2.70850507 2.56726086 4.25867669 4.13042718 3.82280788 3.21918348
 3.42319206 3.48532673 3.72145944 2.47013085 3.89391797 3.83977469
 3.48941671 4.12768494 3.54850563 4.0913825  3.92771986 3.85633822
 3.9018977  4.11408546 3.96852629 2.6847204  2.97143259 3.57415138
 4.04033132 3.12697252 2.35202888 2.73117367 2.95335766 3.89572596
 3.29364535 2.39757755 3.15074274 4.13088495 3.62363714 3.6069587
 3.50619114 3.944679   3.64172082 3.77870728 3.68298742 2.77291846
 3.5881561  3.76400583 4.12722864 3.17509177 3.97477387 3.97909183
 4.30010588 3.45156925 2.11305581 2.66984506 3.04024083 3.62253491
 3.51431427 4.23096841 4.0597576  3.66961901 4.17296689 3.9623175
 3.1659785  3.55775544 3.70877045 4.10780178 3.32423739 4.05295775
 4.17871404 3.35263603 4.01188166 3.01577338 1.61483671 2.61145991
 4.08874514 3.99775428 3.00042857 4.12040888 2.41208355 4.20007407
 1.34589632 3.4086325  4.07047582 3.79264818 1.77221039 3.85529492
 3.49449225 3.10162535 4.57771592 4.11318537 2.32834739 3.26878354
 3.84114456 3.58284824 4.3359916  3.14048624 3.77613493 3.90335542
 2.84784201 3.48893467 3.01953363 1.99502932 3.14714099 2.39741575
 4.05211101 3.43157547 4.06703348 2.22978936 3.84423363 3.47197094
 1.92268098 1.56540741 3.47695848 1.95323409 3.99735355 3.76178748
 2.39410463 2.86745174 3.52125874 3.72786483 2.61880143 3.68562401
 1.86405041 4.1990932  3.90299079 3.84080191 3.96464128 4.19176716
 3.53883388 3.97359947 2.3945885  3.23719195 4.01881621 4.1359343
 4.10244701 3.68386551 1.88152291 2.96071897 1.13126829 3.60750115
 3.28692861 2.37446484 1.11242751 3.27343472 1.1706897  1.73278157
 3.88743613 3.23944252 3.61622055 3.82314441 1.87810014 3.84320287
 3.97987892 4.22743216 4.45778773 3.39999744 2.65592079 3.35095535
 3.66846495 4.01758897 4.06317495 3.24849577 3.64537713 3.76686525
 3.82989891 2.78918284 1.79188315 3.97987892 3.83193419 3.95192679
 2.67463664 4.00782485 4.09978034 3.22657041 3.01172813 3.52250391
 3.57231628 4.00701547 3.03885717 2.75033047 3.99735355 4.10869703
 2.43181394 3.56422963 2.4381973  2.96956732 3.42794158 2.94116154
 2.60526671 4.16725259 3.25077194 3.58258358 2.24989714 3.90481528
 3.9435394  4.36565721 3.34572138 3.75108209 3.3779754  3.89139226
 3.62667456 2.03780063 2.36447459 4.19274087 1.51288103 2.52227155
 4.30608904 2.28513056 3.3788384  3.23363889 2.15660044 3.92697276
 3.77613493 2.61809511 3.11215004 3.828206   3.75453308 3.74608364
 2.15723645 1.53084427 3.01998581 2.98458782 1.05320983 2.76622869
 3.93597507 4.13042718 3.1029349  1.47766878 3.54544128 1.59811158
 2.11812097 1.90137286 3.43567945 2.33539314 3.85425271 3.61567335
 1.88002702 2.80778691 3.23944252 3.10227991 4.17535752 4.1825639
 2.43030805 3.96464128 3.44786211 3.79362809 3.91251467 3.96697047
 4.07220145 3.93484534 3.54086228 3.68094153 3.48941671 3.90335542
 3.61048987 2.65184363 3.32015825 3.77196893 3.17192777 3.34488649
 4.04242468 3.87672557 3.4805363  4.12176911 3.14082644 3.44693746
 3.78031837 2.94969724 2.20693045 3.5587885  3.73277281 3.89608795
 3.76527567 3.25267272 3.35453017 3.59055387 3.02315683 3.22120945
 2.75923484 2.89474286 2.87056297 4.02910225 3.57809512 3.35158528
 3.77838537 2.14471811 3.6069587  3.59751321 4.08349119 3.17333276
 2.56333798 3.57704194 3.6291666  3.57179258 3.98501018 4.08699075
 2.61749008 4.20351472 3.80612414 3.74920474 2.85102005 3.04116433
 3.54111612 4.19615634 3.73000911 3.34321878 3.92622621 1.79613057
 1.96902609 3.59536671 2.84518025 4.37321319 3.99935877 4.1185981
 3.66328806 3.88028302 3.94963234 3.81176544 2.7790607  2.24328819
 3.93597507 4.03657427 2.85817571 3.99976029 3.40176266 3.14406406
 3.59082064 3.82079107 3.95614702 2.28015417 1.22880443 3.12865179
 1.00930295 2.28556446 2.52373904 2.52649639 1.99697863 3.42161388
 2.83761401 1.89078919 4.1990932  2.91979468 3.13742969 2.54385746
 1.1075384  2.89754006 3.00546786 3.18144997 3.66961901 2.87720665
 4.04746671 2.11549365 3.24717039 4.03615769 1.0630024  3.59402748
 2.52631233 3.91583265 4.04620382 4.15123718 3.5959029  3.81143271
 3.75233562 3.46747974 4.04788803 4.13088495 3.51036754 2.6714397
 4.10512081 3.86052232 4.13042718 3.77101    2.11910034 3.18393356
 3.77228877 3.71117502 3.90299079 2.07489623 4.01758897 3.10129824
 4.02868877 4.12449515 4.08349119 1.44203499 3.57415138 3.99255738
 2.55459101 3.53529406 2.90503776 2.47711473 2.54996334 2.30905707
 3.9015336  2.27391468 1.98266423 2.03819592 2.68095391 2.22426354
 2.8652538  4.22441101 1.82724729 3.26588751 2.89713998 3.8842109
 2.39442718 1.36674528 3.22250085 3.59002053 4.04915305 3.91030879
 4.02744936 3.03885717 4.13225952 3.26897691 4.01595498 3.43842482
 3.47791131 2.14717148 4.12722864 3.9712548  3.82280788 3.81743874
 2.96456266 4.06189208 3.43316946 1.6657855  4.09358563 3.25973719
 2.77021369 3.76845735]
['10' 'able' 'about' 'absolutely' 'act' 'acting' 'action' 'actor' 'actors'
 'actually' 'after' 'again' 'against' 'all' 'almost' 'along' 'already'
 'also' 'although' 'always' 'am' 'amazing' 'american' 'an' 'and' 'another'
 'any' 'anyone' 'anything' 'are' 'around' 'as' 'at' 'audience' 'away'
 'awful' 'back' 'bad' 'based' 'be' 'beautiful' 'because' 'become'
 'becomes' 'been' 'before' 'beginning' 'behind' 'being' 'believe' 'best'
 'better' 'between' 'big' 'bit' 'black' 'book' 'boring' 'both' 'boy'
 'budget' 'but' 'by' 'called' 'came' 'camera' 'can' 'cant' 'care' 'case'
 'cast' 'certainly' 'character' 'characters' 'children' 'cinema' 'classic'
 'come' 'comedy' 'comes' 'completely' 'could' 'couldnt' 'couple' 'course'
 'dark' 'day' 'days' 'dead' 'death' 'definitely' 'despite' 'dialogue'
 'did' 'didnt' 'different' 'direction' 'director' 'do' 'does' 'doesnt'
 'doing' 'done' 'dont' 'down' 'drama' 'during' 'dvd' 'each' 'early'
 'effects' 'either' 'else' 'end' 'ending' 'enjoy' 'enjoyed' 'enough'
 'entertaining' 'entire' 'episode' 'especially' 'even' 'ever' 'every'
 'everyone' 'everything' 'evil' 'example' 'excellent' 'expect' 'face'
 'fact' 'family' 'fan' 'fans' 'far' 'father' 'favorite' 'feel' 'felt'
 'few' 'film' 'films' 'final' 'finally' 'find' 'fine' 'first' 'flick'
 'for' 'found' 'friend' 'friends' 'from' 'full' 'fun' 'funny' 'game'
 'gave' 'get' 'gets' 'getting' 'girl' 'girls' 'give' 'given' 'gives' 'go'
 'goes' 'going' 'good' 'got' 'great' 'guess' 'guy' 'guys' 'had' 'half'
 'hard' 'has' 'have' 'having' 'he' 'head' 'help' 'her' 'here' 'hes' 'high'
 'him' 'himself' 'his' 'history' 'hollywood' 'home' 'hope' 'horrible'
 'horror' 'house' 'how' 'however' 'human' 'humor' 'id' 'idea' 'if' 'im'
 'in' 'instead' 'interesting' 'into' 'is' 'isnt' 'it' 'its' 'itself' 'ive'
 'job' 'john' 'just' 'keep' 'kids' 'kill' 'killer' 'kind' 'know' 'last'
 'later' 'laugh' 'lead' 'least' 'left' 'less' 'let' 'life' 'like' 'liked'
 'line' 'lines' 'little' 'live' 'lives' 'long' 'look' 'looking' 'looks'
 'lost' 'lot' 'love' 'loved' 'low' 'made' 'main' 'make' 'makes' 'making'
 'man' 'many' 'matter' 'may' 'maybe' 'me' 'mean' 'men' 'michael' 'might'
 'mind' 'minutes' 'moments' 'money' 'more' 'most' 'mother' 'movie'
 'movies' 'mr' 'much' 'music' 'must' 'my' 'name' 'need' 'never' 'new'
 'next' 'nice' 'night' 'no' 'not' 'nothing' 'now' 'of' 'off' 'often' 'oh'
 'old' 'on' 'once' 'one' 'only' 'or' 'original' 'other' 'others' 'our'
 'out' 'over' 'own' 'part' 'parts' 'past' 'people' 'perfect' 'performance'
 'performances' 'perhaps' 'person' 'picture' 'piece' 'place' 'play'
 'played' 'playing' 'plays' 'plot' 'point' 'poor' 'pretty' 'probably'
 'problem' 'production' 'put' 'quality' 'quite' 'rather' 'read' 'real'
 'really' 'reason' 'recommend' 'remember' 'rest' 'right' 'role' 'said'
 'same' 'saw' 'say' 'scene' 'scenes' 'school' 'screen' 'script' 'second'
 'see' 'seeing' 'seem' 'seemed' 'seems' 'seen' 'sense' 'series' 'set'
 'several' 'sex' 'she' 'shes' 'short' 'shot' 'should' 'show' 'shows'
 'side' 'simply' 'since' 'small' 'so' 'some' 'someone' 'something' 'son'
 'sort' 'sound' 'special' 'star' 'stars' 'start' 'still' 'story' 'stupid'
 'style' 'such' 'supposed' 'sure' 'take' 'takes' 'tell' 'terrible' 'than'
 'that' 'thats' 'the' 'their' 'them' 'then' 'there' 'theres' 'these'
 'they' 'theyre' 'thing' 'things' 'think' 'this' 'those' 'though'
 'thought' 'three' 'through' 'throughout' 'time' 'times' 'title' 'to'
 'together' 'too' 'top' 'totally' 'tries' 'true' 'truly' 'try' 'trying'
 'turn' 'turns' 'tv' 'two' 'under' 'understand' 'unfortunately' 'until'
 'up' 'us' 'use' 'used' 'version' 'very' 'video' 'want' 'wanted' 'wants'
 'war' 'was' 'wasnt' 'waste' 'watch' 'watched' 'watching' 'way' 'we'
 'well' 'went' 'were' 'what' 'when' 'where' 'which' 'while' 'white' 'who'
 'whole' 'why' 'wife' 'will' 'with' 'without' 'woman' 'women' 'wonderful'
 'wont' 'work' 'works' 'world' 'worse' 'worst' 'worth' 'would' 'writing'
 'written' 'wrong' 'year' 'years' 'yes' 'yet' 'you' 'youll' 'young' 'your'
 'youre']

In [51]:
idf_score = tfidf.idf_ 
words = tfidf.get_feature_names_out() 

for word, score in zip(words, idf_score):
    print(word, ":", score)

10 : 3.6453771315637895
able : 4.068322966188829
about : 1.8845698458900952
absolutely : 3.89681232549909
act : 4.178233842949314
acting : 2.5708142886418983
action : 3.48292864692533
actor : 3.6324990140551385
actors : 2.947731770801944
actually : 2.9971813388661106
after : 2.512240461518744
again : 3.114964374522494
against : 4.028275465059554
all : 1.6844056746913751
almost : 3.257058277838078
along : 3.726641586487648
already : 4.044102534295041
also : 2.389198516099756
although : 3.5175324893369178
always : 3.266080318111676
am : 3.3691723370661615
amazing : 4.172012238769353
american : 3.772928773250709
an : 1.725731695233348
and : 1.0366010000630033
another : 2.9854613101926484
any : 2.4822087113186395
anyone : 3.3982353238092986
anything : 3.31265542864755
are : 1.5953873254425748
around : 3.150055694333764
as : 1.4554739902532394
at : 1.6737960186806915
audience : 3.7018893418271315
away : 3.3799181958967184
awful : 3.9258531459743264
back : 2.9202039242844355
bad : 2.4758015274214293
based : 4.0184069639188
be : 1.5786249459872828
beautiful : 3.674248652426702
because : 2.405130275177534
become : 3.9599991036481756
becomes : 4.080874526770829
been : 2.3402708224185664
before : 2.972438408736112
beginning : 3.991760252084456
behind : 4.170581964389653
being : 2.6113597195236995
believe : 3.4457828624703764
best : 2.663914098030162
better : 2.7129313207103793
between : 3.236068568993804
big : 3.2221317086441714
bit : 3.3134638361289244
black : 3.867183172559286
book : 3.9530759990735573
boring : 3.8390904633406167
both : 3.232146629145487
boy : 4.147040387567776
budget : 3.998957404302942
but : 1.3548965617973556
by : 1.7686668897615956
called : 4.06061084570249
came : 3.8031504071524824
camera : 3.934092892967266
can : 2.171202981302948
cant : 3.063273281283314
care : 4.063602940262168
case : 3.9627044193077934
cast : 3.109178756267988
certainly : 3.9469621091845615
character : 2.7085050658353373
characters : 2.5672608635343144
children : 4.258676694680048
cinema : 4.130427176680595
classic : 3.822807878372636
come : 3.219183484654976
comedy : 3.423192055783166
comes : 3.485326729609343
completely : 3.721459438021229
could : 2.470130847013004
couldnt : 3.8939179674727256
couple : 3.839774691899641
course : 3.4894167148608677
dark : 4.127684944614819
day : 3.5485056312308743
days : 4.0913825043692436
dead : 3.927719862962167
death : 3.8563382175713157
definitely : 3.901897697882369
despite : 4.1140854603158585
dialogue : 3.9685262871004023
did : 2.68472039673465
didnt : 2.971432589267739
different : 3.5741513833364253
direction : 4.040331316751962
director : 3.12697252415089
do : 2.352028882953343
does : 2.7311736709181993
doesnt : 2.9533576646841126
doing : 3.895725959286869
done : 3.2936453514225765
dont : 2.3975775531986043
down : 3.1507427434848023
drama : 4.13088494734549
during : 3.6236371449273834
dvd : 3.606958699533801
each : 3.5061911448927274
early : 3.944679003169993
effects : 3.641720820360679
either : 3.7787072805016533
else : 3.6829874205347495
end : 2.772918461387139
ending : 3.5881561042368753
enjoy : 3.764005833232516
enjoyed : 4.12722863614238
enough : 3.175091772495089
entertaining : 3.974773866968802
entire : 3.9790918324608864
episode : 4.300105880093747
especially : 3.4515692459340066
even : 2.1130558091338365
ever : 2.6698450622491983
every : 3.0402408283265574
everyone : 3.62253491279595
everything : 3.5143142664825953
evil : 4.230968405902473
example : 4.059757603329906
excellent : 3.66961901452796
expect : 4.172966892779804
face : 3.9623174972677564
fact : 3.165978495262223
family : 3.5577554402433447
fan : 3.708770446016606
fans : 4.107801777162617
far : 3.3242373929211624
father : 4.052957747124773
favorite : 4.178714035035371
feel : 3.3526360263996136
felt : 4.011881655283878
few : 3.015773381797106
film : 1.614836706953993
films : 2.611459914904776
final : 4.088745140203159
finally : 3.9977542760246667
find : 3.000428574191815
fine : 4.120408877953549
first : 2.412083552813856
flick : 4.200074070427616
for : 1.3458963164965094
found : 3.4086324974395783
friend : 4.07047581954993
friends : 3.7926481773775103
from : 1.772210387700401
full : 3.855294920658738
fun : 3.494492254457704
funny : 3.1016253541815604
game : 4.577715924953324
gave : 4.113185370246089
get : 2.328347385165361
gets : 3.268783544318538
getting : 3.841144555127555
girl : 3.582848236148831
girls : 4.335991596544451
give : 3.1404862433176133
given : 3.776134931816342
gives : 3.903355424088026
go : 2.847842012964598
goes : 3.4889346709855418
going : 3.0195336328999507
good : 1.9950293163855628
got : 3.1471409901699765
great : 2.397415753991067
guess : 4.0521110070233775
guy : 3.4315754740910083
guys : 4.067033475358958
had : 2.2297893591699487
half : 3.844233625715084
hard : 3.4719709384277873
has : 1.9226809786820014
have : 1.565407411558676
having : 3.4769584799388262
he : 1.9532340857787553
head : 3.9973535547209673
help : 3.7617874834082006
her : 2.394104626394956
here : 2.867451740984059
hes : 3.521258738835406
high : 3.727864828230392
him : 2.6188014272372557
himself : 3.685624012072383
his : 1.864050405013073
history : 4.199093197372024
hollywood : 3.9029907932726826
home : 3.840801913356171
hope : 3.964641278328941
horrible : 4.191767157279951
horror : 3.5388338836569133
house : 3.97359946871286
how : 2.3945884973721387
however : 3.2371919542458163
human : 4.0188162129525455
humor : 4.1359343039538565
id : 4.102447012024957
idea : 3.6838655122053954
if : 1.881522906188494
im : 2.960718966328755
in : 1.1312682864099568
instead : 3.607501145980517
interesting : 3.286928613409041
into : 2.374464844562744
is : 1.1124275095195468
isnt : 3.2734347154942682
it : 1.1706897038535098
its : 1.732781570994041
itself : 3.887436129870535
ive : 3.2394425178364084
job : 3.616220547272334
john : 3.823144408747678
just : 1.8781001439104057
keep : 3.8432028748937093
kids : 3.9798789241977035
kill : 4.22743215569049
killer : 4.457787732950552
kind : 3.3999974388026977
know : 2.655920786644444
last : 3.350955353735095
later : 3.6684649463098533
laugh : 4.017588967963168
lead : 4.063174949671428
least : 3.2484957671470163
left : 3.6453771315637895
less : 3.766865247412718
let : 3.8298989092673463
life : 2.7891828431807917
like : 1.7918831532991057
liked : 3.9798789241977035
line : 3.8319341881245985
lines : 3.951926793813964
little : 2.6746366382590976
live : 4.007824854588263
lives : 4.099780343778042
long : 3.2265704065180505
look : 3.011728129445748
looking : 3.522503913943369
looks : 3.5723162799245927
lost : 4.007015465632705
lot : 3.0388571706378986
love : 2.7503304711155185
loved : 3.9973535547209673
low : 4.108697032370127
made : 2.4318139449912595
main : 3.5642296309265395
make : 2.4381973027995736
makes : 2.96956731862147
making : 3.427941584105346
man : 2.941161536780214
many : 2.605266707615635
matter : 4.167252591516365
may : 3.250771944154031
maybe : 3.582583580860797
me : 2.249897136316913
mean : 3.9048152783618915
men : 3.9435394019070595
michael : 4.365657206063608
might : 3.3457213838676765
mind : 3.751082091495504
minutes : 3.377975399818825
moments : 3.891392258029751
money : 3.6266745626982186
more : 2.037800629261868
most : 2.3644745943154373
mother : 4.192740867191352
movie : 1.512881026928064
movies : 2.522271550555187
mr : 4.306089036370581
much : 2.285130555585578
music : 3.3788383987936372
must : 3.2336388883293257
my : 2.156600441823338
name : 3.926972757959168
need : 3.776134931816342
never : 2.6180951056297666
new : 3.1121500361033716
next : 3.8282060021421933
nice : 3.7545330753125534
night : 3.746083643100429
no : 2.157236452784166
not : 1.5308442700726834
nothing : 3.01998581468473
now : 2.9845878205461944
of : 1.0532098283141218
off : 2.766228688184052
often : 3.935975069318133
oh : 4.130427176680595
old : 3.102934897665481
on : 1.4776687788714362
once : 3.5454412774539943
one : 1.5981115784123614
only : 2.1181209650519746
or : 1.9013728593099506
original : 3.4356794470193903
other : 2.335393135741507
others : 3.8542527110802944
our : 3.615673351636245
out : 1.8800270195969109
over : 2.807786907173875
own : 3.2394425178364084
part : 3.102279911560519
parts : 4.175357522653719
past : 4.182563895420813
people : 2.4303080466057834
perfect : 3.964641278328941
performance : 3.4478621054511867
performances : 3.7936280892638594
perhaps : 3.912514674783938
person : 3.9669704719285415
picture : 4.0722014455174005
piece : 3.9348453384504722
place : 3.540862281918306
play : 3.68094153351396
played : 3.4894167148608677
playing : 3.903355424088026
plays : 3.6104898725633485
plot : 2.651843628730541
point : 3.3201582520416375
poor : 3.7719689267524443
pretty : 3.171927769152432
probably : 3.3448864850506546
problem : 4.042424681552424
production : 3.876725566932353
put : 3.48053630128671
quality : 4.12176911393748
quite : 3.140826437231423
rather : 3.4469374636839683
read : 3.780318365109837
real : 2.94969723542456
really : 2.2069304481132814
reason : 3.558788498186458
recommend : 3.7327728135425846
remember : 3.8960879502410486
rest : 3.765275674672992
right : 3.2526727240458393
role : 3.354530165658968
said : 3.5905538674743736
same : 3.0231568252693712
saw : 3.2212094545900545
say : 2.759234837552331
scene : 2.894742860086162
scenes : 2.8705629698354316
school : 4.029102253035548
screen : 3.578095124480467
script : 3.351585275015767
second : 3.7783853748172387
see : 2.1447181126634662
seeing : 3.606958699533801
seem : 3.597513210337569
seemed : 4.083491187662
seems : 3.1733327570899093
seen : 2.56333797662055
sense : 3.5770419384958085
series : 3.629166603306747
set : 3.571792582609665
several : 3.9850101768220916
sex : 4.086990753788265
she : 2.6174900839313673
shes : 4.203514722629901
short : 3.806124141377601
shot : 3.749204744260768
should : 2.8510200490723308
show : 3.0411643315474945
shows : 3.54111612123938
side : 4.196156337698714
simply : 3.730009108420967
since : 3.3432187756793454
small : 3.9262262107053836
so : 1.7961305714180527
some : 1.9690260893461522
someone : 3.595366710989128
something : 2.8451802457551727
son : 4.373213185052561
sort : 3.999358768948105
sound : 4.11859810335284
special : 3.6632880581303193
star : 3.8802830235478796
stars : 3.9496323377404403
start : 3.811765437240978
still : 2.779060696620283
story : 2.243288186733581
stupid : 3.935975069318133
style : 4.036574267874249
such : 2.858175714667743
supposed : 3.9997602947515323
sure : 3.401762664327267
take : 3.144064064665497
takes : 3.5908206408519727
tell : 3.8207910709663313
terrible : 3.956147018761634
than : 2.2801541650915027
that : 1.2288044310042983
thats : 3.1286517856706104
the : 1.0093029533989195
their : 2.28556445781975
them : 2.5237390368315653
then : 2.526496391519756
there : 1.9969786347416125
theres : 3.4216138793762507
these : 2.837614005371857
they : 1.89078919444408
theyre : 4.199093197372024
thing : 2.9197946752506905
things : 3.137429694835064
think : 2.543857455150154
this : 1.1075383975672064
those : 2.897540064707224
though : 3.0054678615715122
thought : 3.181449971237581
three : 3.66961901452796
through : 2.8772066469784336
throughout : 4.047466709040672
time : 2.1154936455435243
times : 3.2471703859059478
title : 4.036157687989032
to : 1.0630023989902713
together : 3.5940274848615523
too : 2.5263123311474343
top : 3.91583265017812
totally : 4.046203816850092
tries : 4.151237176194389
true : 3.595902904031465
truly : 3.811432713897366
try : 3.7523356172002282
trying : 3.4674797359842824
turn : 4.047888027774523
turns : 4.13088494734549
tv : 3.510367542069956
two : 2.671439704589984
under : 4.105120810409359
understand : 3.8605223240938895
unfortunately : 4.130427176680595
until : 3.7710100006760867
up : 2.1191003371079757
us : 3.1839335630765495
use : 3.772288773228864
used : 3.7111750158556918
version : 3.9029907932726826
very : 2.074896230791529
video : 4.017588967963168
want : 3.101298236089013
wanted : 4.028688773600258
wants : 4.1244951492467194
war : 4.083491187662
was : 1.4420349909057504
wasnt : 3.5741513833364253
waste : 3.9925573824574747
watch : 2.554591010793263
watched : 3.5352940569517894
watching : 2.905037756813025
way : 2.47711472524639
we : 2.549963340448463
well : 2.3090570673745474
went : 3.901533598115012
were : 2.273914678430982
what : 1.9826642322241788
when : 2.0381959196642816
where : 2.680953913939173
which : 2.2242635409682983
while : 2.865253795823562
white : 4.2244110053563135
who : 1.827247294933398
whole : 3.2658875098588855
why : 2.897139984685884
wife : 3.8842108986210864
will : 2.394427181030444
with : 1.3667452795922366
without : 3.2225008485523867
woman : 3.5900205341283984
women : 4.0491530500811095
wonderful : 3.910308791536526
wont : 4.027449360097249
work : 3.0388571706378986
works : 4.132259518008657
world : 3.268976911814064
worse : 4.015954980671513
worst : 3.438424815936583
worth : 3.477911314694098
would : 2.147171484132774
writing : 4.12722863614238
written : 3.9712548017536062
wrong : 3.822807878372636
year : 3.817438737957578
years : 2.9645626610033182
yes : 4.061892075858539
yet : 3.4331694628151648
you : 1.6657855036187308
youll : 4.093585633702757
young : 3.2597371925668726
your : 2.770213691113497
youre : 3.768457350917308